// Story element categories. Each key is a category; edit/add items freely.
const CATEGORIES = {
  character: {
    label: "Character",
    items: [
      "A retired superhero who's lost their powers",
      "A small-town librarian with a hidden past",
      "An AI that just became self-aware",
      "A washed-up detective on their last case",
      "A teenager who can talk to ghosts",
      "A con artist trying to go straight",
      "An immortal who's forgotten why they wanted to live forever",
      "A soldier who refuses to fight anymore",
      "A chef who can taste memories in food",
      "A courier who delivers messages between worlds",
      "A scientist whose experiment became sentient",
      "A grieving parent searching for answers",
      "A thief who only steals from the wealthy",
      "A child prodigy burned out by expectations",
      "A lighthouse keeper who sees things in the fog",
      "A former villain seeking redemption",
      "A time traveler stuck in the wrong era",
      "A ship captain who's never lost a crew member",
      "A hermit dragged back into society",
      "A clone questioning their own identity",
      "Spider-Man",
      "Cosmic Plaything that knows they're being fucked with",
      "Danny DeVito",
      "Nicolas Cage",
      "Martha Stewart",
      "Snoop Dogg",
      "Christopher Walken",
      "Keanu Reeves",
      "Gordon Ramsay",
      "Jeff Goldblum",
      "Guy Fieri",
      "Steve Buscemi",
      "Jack Black",
      "Jennifer Coolidge",
      "Willem Dafoe",
      "Dolph Lundgren",
      "Bill Murray",
      "David Attenborough",
      "Ozzy Osbourne",
      "Dolly Parton",
      "Post Malone",
      "Shaquille O'Neal",
      "Gary Busey",
      "Pedro Pascal",
      "Aubrey Plaza",
      "Gilbert Gottfried",
      "Larry David",
      "T-Pain",
      "Flavor Flav",
      "Meat Loaf",
      "Terry Crews",
      "Samuel L. Jackson",
      "Joan Rivers",
      "Mike Tyson",
      "Dennis Rodman",
      "Simon Cowell",
      "Bear Grylls",
      "Steve Irwin",
      "Ric Flair",
      "Gene Simmons",
      "Hulk Hogan",
      "John Cena",
      "Countess Luann",
      "Pauly D",
      "Snooki",
      "Judge Judy",
      "Jerry Springer",
      "Dr. Phil",
      "Billy Mays",
      "Howard Stern",
      "RuPaul",
      "Tommy Wiseau",
      "Monster that's actually just the town's reject",
      "Monster - \"They blamed the murders on me just because I look monstrous\"",
      "A real knight paying the bills by acting at Medieval Times",
      "A real mermaid hiding as an actress at a mermaid bar",
      "Omniscient world hopper",
      "Prescient character that doesn't quite know where the visions come from",
      "I was ordered to be here by a dream lady",
      "Expendable victims",
      "They're a pervert but we need them",
      "A big, screwed-up family that bullies each other, but gets pissed when a member is mildly disrespected",
      "Tiny Tim Template",
      "High hope, zero talent",
      "The only survivor of the Genocide of Gods",
      "I don't want to be the world's best cyber criminal, but hey, I'm good at it",
      "James Bond's girlfriend",
      "The bastard child turned king's assassin",
      "Wait, I don't want to be an assassin",
      "Document forger who plans his own crime",
      "Actor that directs their own movie",
      "Talented person promoted until their out of their depth",
      "Lopin and his cousins",
      "They're an absolute fucker, but we need them",
      "She's a mean girl, but we need her",
      "A loveable nuisance",
      "An unknown, annoying little sister who just hit you up on Instagram",
      "A loving family... but the husband had another family on the side",
      "Man who cheats when he's out of town",
      "Married couple who were affair participants 25 years ago",
      "Child whose parents were in an open 24/7 BDSM relationship",
      "Child whose parents were openly polyamorous",
      "The Dugger Family",
      "Recovering OCD sufferer who keeps a messy house",
      "Flat earther",
      "Hobby newbie that buys the most expensive gear",
      "Young adult - 'My dad just got busted with illegal porn'",
      "Adult - 'My partner just got busted with illegal porn'",
      "Woman who discovered her husband as a secret family on the side",
      "Terrifying mobster with quirky hobbies",
      "Apparent villain that does helpful things",
      "Ugly like monster, y no monster?",
      "The guard that helps you get free",
      "Former Red Shirt who has managed to get enough screen time to make them stand out",
      "Defeated nice guy turned DoomBot",
      "Monster, Hot in Human Form",
      "Dumped Woman: Thanks for leaving me with a child to raise by myself",
      "Man with notoriously large...",
      "Unrefined but lovable country girl",
      "The loser protagonist is you",
      "Protagonist so dumb so that you feel superior to him",
      "Handsome man who just can't figure out how to talk to women",
      "Dungeon Crawler Carl",
      "Princess Donut",
      "Haplessness man appealingly harmless to the girls",
      "The gay man in a girl squad",
      "The only cool guy who can come to girl's night",
      "Begrudging harem leader",
      "The crazy guy... but actually the only sane man who uncovered the frightening horror",
      "A kindly barkeep",
      "Cleopatra",
      "Julius Caesar",
      "Napoleon Bonaparte",
      "Joan of Arc",
      "Leonardo da Vinci",
      "Marie Curie",
      "Nikola Tesla",
      "Albert Einstein",
      "Winston Churchill",
      "Frida Kahlo",
      "Wolfgang Amadeus Mozart",
      "Alexander the Great",
      "Genghis Khan",
      "Queen Victoria",
      "Abraham Lincoln",
      "Harriet Tubman",
      "Benjamin Franklin",
      "Theodore Roosevelt",
      "Salvador Dalí",
      "Pablo Picasso",
      "Vincent van Gogh",
      "George Washington",
      "Rasputin",
      "Edgar Allan Poe",
      "William Shakespeare",
      "Jane Austen",
      "Amelia Earhart",
      "Neil Armstrong",
      "Babe Ruth",
      "Muhammad Ali",
      "Mike Tyson",
      "Marilyn Monroe",
      "Elvis Presley",
      "Freddie Mercury",
      "David Bowie",
      "Prince",
      "Keanu Reeves",
      "Nicolas Cage",
      "Jeff Goldblum",
      "Danny DeVito",
      "Martha Stewart",
      "Snoop Dogg",
      "Guy Fieri",
      "Steve Irwin",
      "Bob Ross",
      "Mr. Rogers",
      "Ozzy Osbourne",
      "Stephen Hawking",
      "Andy Warhol",
      "Houdini",
      "Batman",
      "Superman",
      "Wonder Woman",
      "Iron Man",
      "Captain America",
      "The Hulk",
      "Wolverine",
      "Black Panther",
      "Harry Potter",
      "Hermione Granger",
      "Frodo Baggins",
      "Aragorn",
      "Luke Skywalker",
      "Princess Leia",
      "Han Solo",
      "Katniss Everdeen",
      "Sherlock Holmes",
      "James Bond",
      "Indiana Jones",
      "Ellen Ripley",
      "Sarah Connor",
      "Neo",
      "John Wick",
      "Jon Snow",
      "Daenerys Targaryen",
      "Rocky Balboa",
      "Elsa",
      "Moana",
      "Mulan",
      "Beetlejuice (the dog)",
      "Wicked Witch of the West",
      "Princess Bride",
      "The Witcher",
      "Neil Gaiman",
      "A fascist police dog",
      "Snape",
      "Dumbledor",
      "Ebenezer Scrooge",
      "Soulmates fated to kill each other",
      "Romeo and/or Juliet",
      "Peter Pan",
      "Murder Robot",
      "Nancy Drew",
      "Lindsey Clancy",
      "A talking dragon who guards a magical gate in the middle of the harbor",
      "A serial killer, but he's kinda right...",
      "A loyal bodyguard in love with his ward's wife",
      "An assassin of the Catholic church",
      "A sex club owner",
      "Akasha, Queen of the Damned",
      "Omniscient, unknowable horror",
      "An invisible person trying desperately to communicate",
      "Astarion",
      "A prostitute who's trying to get into law enforcement, but keeps getting rejected",
      "A self-help guru",
      "A TikTok astrologer receiving signals from street lamps",
      "Caligula",
      "An Instagram influencer",
      "A group of awful jocks bullying you",
      "A masked hero, and you just know he's hot",
      "Gordon Ramsey",
      "Villain who is selectively nice to very specific people",
      "A good kid pressured into altering records to commit a crime",
      "Someone born to provide harvested organs",
      "An organ harvester who contracts HIV from a sale",
      "Barbie",
      "A duty-bound knight who just keeps fuckin' (hates himself)",
      "A duty-bound knight who cannot stop accidentally killing his wards",
      "Nightmare neighbor with numerous weapons charges",
      "Stuart Little",
      "A plucky teenager who keeps getting thrown in prison (did they commit the crime???)",
      "A guy who SOMEHOW keeps escaping prison",
      "A stern man that just wants to be SENT HOME",
      "Someone missing their favorite show on TV",
      "Falsely accused, just released",
      "Fitness guru, but doesn't know they're a demigod",
      "Simba",
      "A bureaucrat enforcing an unjust law",
      "A former ally who now sees things differently",
      "A force of nature given a will of its own",
      "An idealist willing to do anything for their cause",
      "A version of the protagonist from another timeline",
      "A version of themself from another timeline",
      "A corporation that owns the concept of memory",
      "A god who wants to be forgotten",
      "An AI optimizing for the wrong outcome",
      "A parent who won't let go",
      "A cult that believes the end is a gift",
      "A rival who is simply better, most of the time",
      "Society itself, and its quiet cruelties",
      "A monster that used to be human",
      "A judge who is never wrong, and never merciful",
      "A beautiful statue, come to life",
      "Icarus",
      "Darth Vader",
      "Emperor Palpatine",
      "Voldemort",
      "Sauron",
      "The Joker",
      "Thanos",
      "Magneto",
      "Lex Luthor",
      "A prince on the run",
      "An oppressed race with a rich culture",
      "Green Goblin",
      "Doctor Doom",
      "Loki",
      "Hannibal Lecter",
      "Dracula",
      "Freddy Krueger",
      "Michael Myers",
      "Agent Smith",
      "The Terminator",
      "HAL 9000",
      "A nymphomaniac sex slave",
      "A newly-freed slave",
      "Cruella de Vil",
      "Ursula",
      "Maleficent",
      "Scar",
      "Jafar",
      "Bane",
      "Ramsay Bolton",
      "Cersei Lannister",
      "Moriarty",
      "Gollum",
      "The Gladiator",
      "Pete Davidson",
      "Charli XCX",
      "Obama",
      "Ariana Grande",
      "Frankenstein",
      "Moby Dick (the guy)",
      "Moby Dick (the whale)",
      "Straight-passing gay person",
      "Gay-passing straight person who just wants to fit in",
      "A giant",
      "A twink that doesn't know how he got here",
      "Bella",
      "An absolute diva",
      "A gym bro",
      "Buzz Lightyear",
      "Miss Piggy",
      "Kermit",
      "Paul Atreides",
      "A cursed man who does everything to thwart fate",
      "False messiah",
      "James Bond",
      "An all-around good guy not expecting to get thrust into this nonsense",
      "A Warhammer 40k player",
      "A notorious liar",
      "He's the Chosen One... but is mad about it",
      "A poacher",
      "A MAGA convert",
      "Another character's evil counterpart",
      "A compulsive thief",
      "An apprentice and their teacher",
      "Rand al'Thor",
      "Moiraine and Lan",
      "Legolas",
      "A mystic (stinky hippie with dreads)",
      "An oracle that's too beautiful for words",
      "A mystic addicted to the drug they need to see the future",
      "A foster kid",
      "A hot CEO",
      "Sexy Demon",
      "Cannibal Demon",
      "Real estate agent",
      "Peter Lister",
      "David Hertel",
      "Circus performer",
      "A goth DJ",
      "The Hulk (reformed)",
      "The leader of a frat initiation ritual",
      "Nancy Grace",
      "Fox News anchor",
      "Soup kitchen chef with a secret",
      "Jacob",
      "Edward",
      "A magical baby",
      "A baby you REALLY don't want to be around",
      "A child who knows more than they let on",
      "An estranged sibling seeking reconciliation",
      "A rival turned reluctant ally",
      "A mentor hiding a terminal secret",
      "Really nice guy who hates only you",
      "Himbo CEO who runs business into the ground",
      "Someone faking amnesia",
      "The antagonist's sibling",
      "A classroom of college kids",
      "An after-hours adult-learning Spanish class",
      "A line cook",
      "A stranger who shows up at the worst/best moment",
      "An animal companion who understands more than expected",
      "A bureaucrat quietly helping from the shadows",
      "An old flame with unfinished business",
      "A ghost who won't move on until a debt is settled",
      "A con artist who becomes an unlikely friend",
      "Hot preacher sent to convert by all means necessary",
      "Unhot preacher sent to convert by all means necessary",
      "Hot nun who loves her God",
      "Unhot nun who loves to sin",
      "A newly-elected figurehead to a powerful religion",
      "A sentient object that wants to be destoryed",
      "Mermaid, wishing for legs",
      "A girl boosting her self esteem by sleeping with priests",
      "Vindictive clergy",
      "Bad actions, but he's a good guy",
      "A sentient bug",
      "Michael Scott",
      "Ron Swanson",
      "Leslie Knope",
      "Dwight Schrute",
      "Homer Simpson",
      "SpongeBob SquarePants",
      "Shrek",
      "Jack Sparrow",
      "Buffy Summers",
      "Walter White",
      "Tony Soprano",
      "Ross Geller",
      "Ferris Bueller",
      "Napoleon Dynamite",
      "Marty McFly",
      "The Dude",
      "Forrest Gump",
      "Tyrion Lannister",
      "Ash Ketchum",
      "Goku",
      "Naruto Uzumaki",
      "Deadpool",
      "Star-Lord",
      "Michael Jordan",
      "Oprah Winfrey",
      "Barack Obama",
      "Steve Jobs",
      "Beyoncé",
      "Taylor Swift",
      "Kanye West",
      "Britney Spears",
      "Michael Jackson",
      "Tom Brady",
      "LeBron James",
      "Dwayne \"The Rock\" Johnson",
      "Will Smith",
      "Justin Bieber",
      "Lady Gaga",
      "Serena Williams",
      "Mark Zuckerberg",
      "Elon Musk",
      "Ellen DeGeneres",
      "Eminem",
      "The casanova",
      "The hopeless romantic",
      "The boy next door",
      "The girl next door",
      "The alpha bitch",
      "The sex god",
      "The chaste hero",
      "The virgin queen",
      "The slut hero",
      "The slut queen",
      "The seducer",
      "The secret admirer",
      "The jealous ex",
      "The trophy spouse",
      "The sexpot",
      "The intimidating beauty",
      "The unattainable crush",
      "The devoted spouse",
      "The playgirl",
      "The heartbreaker",
      "The romance novel hero",
      "The brooding billionaire",
      "The shy wallflower",
      "The flirtatious rogue",
      "The starcrossed lover",
      "The childhood friend",
      "The stern dominant",
      "The willing submissive",
      "The reluctant courtesan",
      "The seductive enemy",
      "The matchmaker",
      "The serial monogamist",
      "The hopeless flirt",
      "The chivalrous knight",
      "The femme fatale with a heart of gold",
      "The naive maiden",
      "The sensual siren",
      "The overprotective lover",
      "The forbidden attraction",
      "The reformed rake",
      "The confused closeted lover",
      "The passionate rebel",
      "The ice queen/king",
      "The sugar daddy/mommy",
      "The accidental match",
      "The distant husband/wife",
      "The seductive shape-shifter",
      "Anti-Hero that actually wants to be heroic",
      "The Chosen One who doesn't believe in fate",
      "Mentor who did not pass the qualification exam",
      "Lovable rogue, reforming playboy",
      "Femme Fatale that isn't fatal (yet)",
      "Gentle Giant that's wicked smart",
      "Hard-Boiled Detective who doesn't understand saving things in the cloud",
      "Mad scientist publishing to https://pubmed.ncbi.nlm.nih.gov",
      "Reluctant hero that reluctant for medial reasons",
      "Knight errant weeb, obsessed with anime",
      "Jerk with a heart of gold, but only during D&D",
      "Tragic villain, but the tragedy is exaggerated",
      "Noble savage, but he's a white guy on an alien planet",
      "Twitch streamer damsel in doxxing distress",
      "Fallen hero, falsely accused",
      "Crouching Tiger, Hidden Badass",
      "The trickster disguised as close-up magician",
      "The ignored doomsayer that's actually correct",
      "Bad Boy with a heart of gold (literally a metal heart)",
      "The Manic Pixie Dream Girl, who's actually a manic pixie with prophetic dreams",
      "The Stoic that's kinda dumb",
      "WWII Veteran",
      "By-the-Book Cop, but the book is corrupt",
      "The Deadpan Snarker Boomer",
      "The Corrupt Politician",
      "The Mad King on SSRIs",
      "The Wandering Scholar, homeless shelter surfing",
      "The Sympathetic Monster with babies back in the cave",
      "The Reluctant Monster, Fascism Dog",
      "The False Prophet that doesn't know he's false",
      "A Fallen stripper named Angel",
      "The Drunken Master, magical opiates",
      "The Well-Intentioned Extremist... but they're kinda right",
      "The Benevolent Dictator",
      "The Rebellious Princess, who actually isn't a princess",
      "The Shadow Ruler that's literally a shadow",
      "The Bloodthirsty Berserker that's literally a vampire",
      "The Gentle Soul with a curse that hurts people",
      "The Street Urchin with a photographic memory",
      "The Disgraceful Heir, incest",
      "The Eccentric Millionaire, Bitcoin",
      "The Guilt-Ridden Survivor",
      "The Ghost of the Past Self",
      "The Unwilling Vessel of sex",
      "The Cold Strategist",
      "The Naive Idealist",
      "The Weary Mercenary",
      "The Cynical Journalist turned influencer",
      "The Cursed Wanderer",
      "The Outcast Prodigy",
      "The Overzealous Paladin",
      "The Ruthless Executive",
      "The Fanatical Cultist",
      "The Reformed Assassin",
      "The Silent Guardian",
      "The Tragic Clown",
      "The Charismatic Cult Leader",
      "The Reluctant Monarch",
      "The Blind Seer",
      "The Forgotten Hero",
      "The Fallen Knight",
      "The Enigmatic Stranger",
      "The Haunted Scholar",
      "The Exiled Prince",
      "The Masked Vigilante",
      "The Unsung Hero",
      "The Vengeful Orphan",
      "The Ambitious Alchemist",
      "The Broken Soldier",
      "The Carefree Nomad",
      "The Cunning Smuggler",
      "The Desperate Fugitive",
      "The Fatalistic Warrior",
      "The Feared Warlord",
      "The High-Functioning Lunatic",
      "The Honor-Bound Rival",
      "The Incompetent Henchman",
      "The Mysterious Benefactor who doesn't know how the Cloud works",
      "The Obsessive Tracker impressed with Airtags",
      "The Philosophical Monster that carefully weighs crime motive",
      "The Reclusive Genius",
      "A whipping boy, actually a masochist",
      "The Stern Mentor",
      "The Tragic Genius",
      "The Unhinged Rebel",
      "The World-Weary Sheriff",
      "The Zealous Inquisitor",
      "The Apathetic God",
      "The Bound Demon",
      "The False Messiah",
      "Rihanna",
      "The sentient piece of furniture with romantic ambitions",
      "The hyper-specific fetish demon",
      "The sentient creation who falls in love with it's creator",
      "The competitive power couple",
      "The eldritch abomination trying to figure out the internet",
      "The time-traveling Victorian prude completely overwhelmed by modern dating",
      "The vampire who is severely allergic to blood",
      "The ghost who refuses to leave because the living room decor is tacky",
      "The werewolf who only turns into a slightly fluffier Golden Retriever",
      "The actor who won't break character during real-life intimate moments",
      "The serial killer whose only love language is aggressively dynamic organization",
      "The bodybuilder whose muscles are individually sentient and have opinionated personalities",
      "The superhero whose only superpower is generating perfect ambient lighting",
      "The evil overlord who gets severe stage fright before monologuing",
      "The sentient AI that falls in love with a smart toaster",
      "The noir detective who hyperfixates on mundane details",
      "The immortal who keeps accidentally dating their own reincarnated self",
      "The sex worker who is actually deeply afraid of germs",
      "The thief who only loots niche mundane items",
      "The reverse-mermaid (fish top, human legs) struggling to find love on land",
      "The magical girl whose Tinkerbell constantly judges her dating choices",
      "The necromancer who uses undead minions as mundane errand-runners",
      "The shape-shifter who gets stuck halfway between human and beast form during a kiss",
      "The alien spy who misunderstands human hand-holding as a battle duel",
      "The cursed prince who turns into a mundane item",
      "The sentient cloud of gas looking for a long-term relationship",
      "Guitarist who treats romance like an arena concert",
      "The extreme couponer who refuses to pay for a second date on principle",
      "The demon lord who is completely submissive to a retail customer service worker",
      "The tax auditor who gets sexually aroused by impeccably organized spreadsheets",
      "The time-traveler who accidentally becomes their own great-great-grandmother's rival",
      "The haunted mannequin trying to establish a boundaries-based relationship",
      "The professional LARPER who slowly gets possessed by their persona",
      "A furry who's actually a shapeshifter",
      "The succubus who actually just wants to cuddle",
      "The swamp monster who gets a high-fashion glow-up",
      "The telepath who can only read their partner's thoughts about dinner choices",
      "The medieval peasant transported to modern day who thinks a microwave is a god of passion",
      "The dragon who hoards mundane items instead of gold",
      "The sentient mannequin",
      "The professional mascot who develops an alternate personality",
      "The warlord with battle superstitions",
      "The cosmic entity who wants the human experience",
      "The vampire who doesn't see their reflection in the mirror during sex",
      "The guy who is convinced his partner is an undercover spy, but she's just autistic",
      "The superhero who accidentally destroys furniture every time they get aroused",
      "The clone who is deeply in love with their original self's twin sibling",
      "The poltergeist who expresses affection by aggressively throwing plushies",
      "A large monster trying to navigate a narrow apartment for a romantic evening",
      "The mad scientist who accidentally clones their crush into an entire choir",
      "The sentient shadow that gives unsolicited relationship advice during dates"
    ]
  },
  setting: {
    label: "Setting",
    items: [
      "Magical School for Exploited Youngsters",
      "The back room of an abandoned Spirit Halloween",
      "The VIP booth at an Arby's",
      "Inside a broken portal-potty at a 3-day rave",
      "The driver's seat of a runaway Zamboni",
      "The ball pit at a Chuck E. Cheese at 2:00 AM",
      "Inside the trunk of a 1997 Honda Civic",
      "A crowded DMV line on a humid Tuesday",
      "The smoking patio of a low-tier casino",
      "An overcrowded Chuck E. Cheese on a Saturday afternoon",
      "Inside an overgrown, rusting carnival ferris wheel",
      "The breakroom of a struggling Dollar General",
      "A damp crawlspace beneath a haunted Waffle House",
      "The roof of a local IHOP during a thunderstorm",
      "Inside a giant, inflatable bounce-house kingdom",
      "A sketchy, 24-hour tanning salon",
      "The back aisle of a shady adult video store",
      "Inside an operational industrial dishwasher",
      "A subterranean sewer pipe filled with glowing slime",
      "The communal shower room of an elite country club",
      "A discount mattress store that is definitely a money laundering front",
      "The lobby of a sketchy 1-star motel",
      "The interior of a stretched limousine with a leaking sunroof",
      "An abandoned indoor mall fountain",
      "Inside a giant fiberglass peanut on the side of the highway",
      "The waiting area of an emergency vet clinic",
      "A cramped DJ booth at a medieval-themed nightclub",
      "The luggage carousel at a chaotic airport",
      "A damp, windowless basement used for amateur wrestling",
      "Inside an abandoned, rusting submarine",
      "The top shelf of a giant walk-in pantry",
      "An illegal, underground bingo parlor",
      "The back seat of a rideshare driver who won't stop talking",
      "A makeshift sauna built inside an old shed",
      "Inside a giant, hollowed-out parade float",
      "An outdoor porta-potty in the middle of the Sahara Desert",
      "The lost-and-found closet of a high school",
      "A rooftop bar with a broken elevator and one toilet",
      "The mechanical room beneath a wave pool",
      "Inside a pitch-black sensory deprivation tank",
      "An overgrown mini-golf course populated by feral cats",
      "The backstage area of a regional puppet show",
      "A tiny, airless elevator stuck between floors 13 and 14",
      "An abandoned, flooded bowling alley",
      "The control room of a failing nuclear plant",
      "Inside a giant, walk-in freezer full of frozen pizzas",
      "A roadside attraction dedicated to the world's largest ball of lint",
      "The VIP section of a mud-wrestling tournament",
      "An underground bunker stocked entirely with canned beans",
      "The roof of an active city bus",
      "Inside the costume closet of a community theater company",
      "Dance studio",
      "Martial arts dojo",
      "Agrarian America",
      "Breeding cages",
      "Livestock auction - you're the livestock",
      "Livestock auction - the livestock is sentient",
      "The walk-in cheese humidor of a bankrupt dairy conglomerate",
      "A poorly ventilated basement where illegal vape juices are mixed",
      "The observation deck of an abandoned offshore oil rig in a hurricane",
      "A subterranean fallout shelter decorated entirely in 1970s shag carpet",
      "The luggage carousel area of an empty airport terminal at 4:00 AM",
      "A high-stakes bingo hall in a retirement community during a blackout",
      "Inside the control booth of a failing local access cable network",
      "The maintenance tunnels beneath an indoor waterpark in December",
      "An eccentric billionaire's private underground model train bunker",
      "The back storage room of a discount mattress outlet",
      "A 24-hour laundromat during an unseasonal hailstorm",
      "The top floor of an unfinished Brutalist skyscraper",
      "An abandoned roadside dinosaur attraction off Route 66",
      "A crowded sauna where everyone refuses to make eye contact",
      "A decommissioned nuclear missile silo converted into an Airbnb",
      "The employee breakroom of a 24-hour mega-pharmacy",
      "A floating dock in the middle of a swamp at dusk",
      "The kitchen of a seafood buffet five minutes before closing",
      "An illegal rooftop pigeon coop overlooking a neon-lit alleyway",
      "The boiler room of a 120-year-old municipal library",
      "A dilapidated drive-in movie theater overrun by feral peacocks",
      "TheVIP lounge of an underground illegal arm-wrestling tournament",
      "A cramped ferry engine room during rough seas",
      "An antique clock repair shop during the midday chime",
      "The grease pit beneath a quick-lube automotive garage",
      "A dusty taxidermy museum with failing fluorescent tube lights",
      "A decommissioned submarine docked behind a sketchy casino",
      "The basement archives of a small-town historical society",
      "An oversized commercial greenhouse full of overgrown ferns and fog",
      "A roadside petting zoo during an aggressive goat feeding frenzy",
      "The back row of a budget airline flight experiencing severe turbulence",
      "An abandoned municipal water treatment facility",
      "The loading dock behind a failing regional shopping mall",
      "A subterranean wine cellar with a suspiciously locked iron grate",
      "A carnival funhouse mirror maze that has lost power",
      "The roof of a commercial poultry barn during a lightning storm",
      "An all-night diner booth sticky with maple syrup and regret",
      "The VIP box at a low-tier demolition derby",
      "An underground hydro-electric turbine chamber",
      "A dimly lit back-alley tailor shop specializing in quick alterations",
      "A chaotic prep kitchen during a 500-person wedding banquet",
      "A derelict lighthouse whose automated beacon rotates too fast",
      "The back of a moving livestock truck stuck in traffic",
      "A subterranean mushroom farm in a disused railway tunnel",
      "The holding pen of an animal control facility on a full moon",
      "An uninsulated attic full of vintage mannequin limbs",
      "A roadside tire fire burning near an abandoned motel",
      "The crawlspace beneath a historic courthouse",
      "A high-end private kennel during feeding time",
      "A city that rearranges itself every night",
      "The last library on Earth",
      "A generation ship nearing its destination",
      "A small coastal town where the tide never goes out",
      "The border between two warring kingdoms",
      "A university for retired gods",
      "An underground railway that runs through time",
      "A never-ending story that traps its readers",
      "A floating market above the clouds",
      "A post-apocalyptic greenhouse city",
      "A carnival that only appears once a decade",
      "The inside of a dying star",
      "A village where everyone shares one dream",
      "A courtroom that judges fictional characters",
      "An archive of forgotten memories",
      "A desert where sound turns solid",
      "A hotel that exists between dimensions",
      "A subway system with no exits",
      "A frozen ocean hiding a sunken civilization",
      "A theater where the plays predict the future",
      "A labyrinth (sexy)",
      "A law firm",
      "Military academy in space",
      "A magical academy tucked away from sight",
      "Little House on the Prairie",
      "Wuthering Heights",
      "Jurassic Park",
      "Waffle House",
      "Southern Gothic Waffle House",
      "Wonderland (Alice)",
      "Paradise (trying to eat you)",
      "Paradise (seems alright!)",
      "Treasure Island",
      "Mystical location of ascension",
      "BDSM society",
      "Monster fighting pits",
      "Battle planet",
      "The inside of a leviathan brain",
      "A dying planet",
      "Our dad's abandoned throne room",
      "A castle that wants to keep you hostage",
      "A castle that wants you to fuuuuuuuuuuuuck",
      "A thriving planet... but where are the living creatures?",
      "A walled city",
      "A coliseum",
      "A labyrinth (scary)",
      "Yellowstone National Park",
      "Monster's Inc",
      "Haunted Hotel",
      "Luxury Train",
      "Surveillance State",
      "Magical world hidden in plain sight",
      "A dirt and stick house, hastily assembled",
      "Desert",
      "Pawn Shop",
      "Vaguely Scottish magic land",
      "Mr Roger's Neighborhood",
      "The Underworld",
      "A sweaty basement",
      "A post-catastrophe city with a giant hole in the middle",
      "A shitty apartment with a negligent landlord",
      "The planet from Dune",
      "Nursing home",
      "The honeymoon suite",
      "Love motel",
      "The high school prom",
      "The romantic balcony",
      "Secluded beach cove",
      "Cozy cabin in the woods",
      "The bdsm club",
      "The grand ballroom",
      "The rooftop at sunset",
      "The rose garden",
      "Rainy bus stop",
      "The dimly lit bar",
      "Private yacht",
      "The paris cafe",
      "The hot spring / onsen",
      "The steamy shower",
      "The elevator trapped together",
      "The secret hideaway",
      "The bed & breakfast",
      "A secluded waterfall",
      "The candlelit restaurant",
      "The midnight masquerade",
      "The destination wedding",
      "The shared bed in an inn",
      "The speakeasy backroom",
      "The lovers' lane",
      "The velvet-draped boudoir",
      "The romantic vineyard",
      "The enchanted meadow",
      "The vip lounge",
      "The midnight garden",
      "The snowed-in cottage",
      "The ferris wheel at night",
      "The private penthouse",
      "The exotic island resort",
      "The royal bedchamber",
      "The lakeside dock",
      "The backseat of the car",
      "The cozy fireplace nook",
      "The undercover safehouse bed",
      "The steam room",
      "The carnival at twilight",
      "The sunlit botanical conservatory",
      "The private screening room",
      "The moonlit pier",
      "The venetian gondola",
      "The secret meeting place",
      "The opulent palace bedroom",
      "The underground club",
      "The warm blanket fort",
      "Archaeology that hint at magic",
      "City in a Bottle",
      "Garden of Evil",
      "The Future Is Noir",
      "Ghost Town",
      "The Underworld (bad)",
      "The Underworld (good)",
      "Dystopian Metropolis",
      "The Lost City",
      "Floating Castle",
      "Space Station Alpha",
      "Subterranean World",
      "Magical High School",
      "The ever-shifting creepy mansion",
      "Post-Apocalyptic Wasteland",
      "Ancient Temple Ruins",
      "Cyberpunk Slums",
      "Overgrown Wilderness",
      "Interdimensional Hub",
      "The Infinite Library",
      "Cursed Battlefield",
      "Enchanted Forest",
      "Clockwork City",
      "Underwater Utopia",
      "Corrupt Empire's Capital",
      "Desert Oasis of Sin",
      "The Isolated Citadel",
      "Sunken Megacity",
      "Shattered Realm",
      "Volcano Lair",
      "Frozen Tundra Outpost",
      "The Endless Highway",
      "Abandoned Research Facility",
      "Celestial Realm",
      "The Shadow Plane",
      "Carnival of Terrors",
      "Sanitarium of Horror",
      "The Megastructure",
      "Virtual Reality Grid",
      "Microscopic Kingdom",
      "Parallel Earth",
      "The Dying Star",
      "Living Island",
      "Colonial Frontier",
      "Sovereign Airship",
      "Feudal Stronghold",
      "The Void Between Worlds",
      "Sunken Cathedral",
      "The Necropolis",
      "Decadent Palace",
      "The Astral Plane",
      "Gothic Cathedral City",
      "Radioactive Crater",
      "Orbital Habitat",
      "Underground Resistance Base",
      "Industrial Factory Hellscape",
      "Haunted Asylum",
      "Space Graveyard",
      "Walled Sanctuary",
      "Floating Archipelago",
      "Alien Hivelord Domain",
      "Labyrinthine Dungeon",
      "Steampunk Laboratory",
      "The Abyss",
      "Endless Ocean Realm",
      "Haunted Battlefield",
      "Shattered Spire",
      "Submerged Metropolis",
      "Twilight Realm",
      "The Memory Archives",
      "The Iron Fortress",
      "Cursed Swamp",
      "Frozen Abyss",
      "The Glass Desert",
      "The Emerald City",
      "The Celestial Tower",
      "Subterranean Hive",
      "Blood Sea",
      "Crystal Cavern",
      "Phantom Ship",
      "Mechanical Maze",
      "Obsidian Keep",
      "Forgotten Valley",
      "Sunken Ruin",
      "Sky Citadel",
      "Temporal Rift",
      "Burning Sands",
      "Mist-Shrouded Isle",
      "Hollow Mountain",
      "Shattered Cosmos",
      "Fallen Metropolis",
      "Enchanted Oasis",
      "Nightmare Realm",
      "Eternal Battlefield",
      "Cosmic Forge",
      "The back of a bouncy castle during a thunderstorm",
      "A ship that actively sabotages characters it dislikes",
      "Inside an oversized, operational forge",
      "The ball pit of a abandoned 1990s fast food restaurant",
      "A time-loop trapped inside a suburban DMV waiting room",
      "The roof of a moving high-speed bullet train during a meteor shower",
      "An underground lair made entirely of rejected IKEA furniture",
      "The inside of a gigantic, living whale's stomach converted into smuggling ship",
      "An aggressively-themed escape room where you can't leave until you fuuuuuuuuuuuuck",
      "The VIP lounge of a subterranean goblin rave",
      "A haunted laundromat at 3:00 AM where the dryers whisper secrets",
      "The interior of a magical miniature snow globe during an avalanche",
      "A luxury glamping tent in the middle of an active volcano",
      "An interdimensional tollbooth where the fee is a passionate confession",
      "The basement of a wax museum where the statues keep moving when you aren't looking",
      "A high-stakes underground illegal tax-preparation ring",
      "The top of a giant radioactive hamster wheel powering a metropolis",
      "A temporal rift located entirely within a walk-in freezer at a Wendy's",
      "The dreamscape of a very stressed-out golden retriever",
      "A floating sky-castle made entirely out of stale cotton candy",
      "An abandoned theme park ride based on 19th-century dental procedures",
      "A secret room behind the cereal aisle in a 24-hour supermarket",
      "The interior of a giant mech suit during a high-stakes battle",
      "A pocket dimension that looks exactly like a 1990s Windows screen-saver",
      "A cursed hot tub that teleports you to random historical events when you splash",
      "An underwater glass dome inside a hyper-intelligent octopus colony",
      "The middle of an intense, televised professional hide-and-seek tournament",
      "A botanical garden where all the plants aggressively make kissing noises",
      "The waiting room of a celestial court for minor clerical errors",
      "An overgrown gothic cemetery where the ghosts hand out free relationship counseling",
      "A runaway carriage driven by a panicked, sentient goose",
      "The interior of a giant hollowed-out disco ball suspended over a ravine",
      "A magical library where the books actively try to trip lovers into each other",
      "A high-security vault containing the world's last remaining bar of chocolate",
      "The backstage dressing room of an intergalactic drag show",
      "A luxury treehouse built inside a giant, carnivorous venus flytrap",
      "An illegally operated submarine converted into a floating jazz club",
      "The roof of a cathedral surrounded by gargoyles giving commentary",
      "A secret laboratory dedicated to recreating the world's most alluring perfume",
      "A temporal junction where it is perpetually 11:59 PM on New Year's Eve",
      "The inside of a hyper-dimensional closet that changes size based on arousal",
      "An abandoned subterranean subway tunnel filled with glowing bioluminescent mushrooms",
      "The main arena of a gladiatorial combat ring redecorated for a candlelit dinner",
      "A high-end spa operated exclusively by trained capybara therapists",
      "A floating raft made of inflatable flamingo pool floats in the Bermuda Triangle",
      "The top floor of a skyscraper that is slowly tilting over like Jenga",
      "A mystical crossroads where you can trade your soul for a really good date",
      "The inside of a gigantic organ instrument while a dramatic piece is being played",
      "A high-tech VR simulation that keeps glitching into a cheap 8-bit dating sim"
    ]
  },
  conflict: {
    label: "Conflict",
    items: [
      "Man vs. a Past Self that was better than you",
      "Accidentally selling a stolen municipal street sweeper to an undercover cop",
      "Trying to maintain eye contact while wearing a ridiculous mascot head",
      "Realizing mid-hug that you've severely misjudged the social hierarchy",
      "Accidentally replying-all to a company-wide email with your deepest secret",
      "Trying to silently open a bag of sunchips in a dead-silent auditorium",
      "A high-stakes debate over who gets the last piece of garlic bread",
      "Getting your hand permanently stuck in a Pringles can during an emergency",
      "Accidentally joining a competitive air-guitar league",
      "Trying to convince your landlord that the ghost in the kitchen is paying rent",
      "A fierce custody battle over a shared animal shelter cat",
      "Getting caught trying to steal a handful of decorative mints",
      "A tense standoff over who gets to sit in the front seat",
      "Accidentally swallowing a lucky coin right before the big game",
      "Trying to play off a loud, wet fart as a shoe scuff",
      "A feud with a neighbor who keeps mowing your lawn at 5:00 AM",
      "Realizing you've been wearing your shirt inside out for a job interview",
      "Getting trapped in a conversation with someone who only communicates in puns",
      "A bitter legal battle over a disputed fantasy football league payout",
      "Trying to hide an aggressive case of hiccups during a solemn ceremony",
      "Accidentally waving back at someone who was waving at the person behind you",
      "Trying to eat a hard-shell taco quietly during a tense moment",
      "Getting caught in a lie about knowing how to ride a unicycle",
      "A fierce rivalry over who gets to blow out the candles on someone else's cake",
      "Trying to casually escape a room after setting off a smoke alarm with toast",
      "Accidentally sending a spicy text to your family group chat",
      "A desperate search for a bathroom while wearing a complex jumpsuit",
      "Getting your sleeve caught on a doorknob while already furious",
      "Trying to look cool while getting aggressively attacked by a single bee",
      "A dispute over who owns the rights to a hyper-specific meme idea",
      "Accidentally liking a 7-year-old photo on your ex's social media",
      "Trying to explain why there is a live raccoon in your duffel bag",
      "Getting caught using a fake accent to get free samples at the market",
      "A high-stakes game of rock-paper-scissors with your entire life savings on the line",
      "Trying to walk normally after your leg completely falls asleep",
      "Accidentally wearing matching outfits with your arch-nemesis to a party",
      "A feud with a local crow flock that has declared war on you",
      "Trying to keep a straight face while someone explains their terrible startup idea",
      "Getting stuck in a loop of 'no, after you' at a narrow doorway",
      "Accidentally buying 500 pounds of bananas due to a typo online",
      "Trying to hide the fact that you don't know how to whistle",
      "A bitter argument over whether hot dogs count as sandwiches",
      "Getting caught lip-syncing passionately to a song you claimed to hate",
      "Trying to subtly untangle your headphones while someone is yelling at you",
      "Accidentally wearing two completely different shoes to an important event",
      "A standoff with a vending machine that took your last dollar without dropping the chips",
      "Trying to act natural while carrying an awkwardly large framed portrait of yourself",
      "Getting trapped in an endless polite conversation with a door-to-door salesman",
      "Accidentally spilling hot soup directly into your own shoe",
      "Trying to convince everyone that you didn't just break the heirloom vase",
      "A desperate struggle to remember someone's name while introducing them to your boss",
      "Getting caught sneaking snacks into a theater under an oversized trench coat",
      "You must keep a pet raccoon quiet",
      "Both of you claimed the exact same winning lottery ticket found in a drain",
      "Trying to pass off a frozen turkey as a bowling ball to win a bet",
      "An aggressive HOA inspector is actively measuring your lawn with calipers",
      "You are trapped in an elevator with your ex and their tax auditor",
      "A rogue goat has eaten your only copy of a signed real estate deed",
      "Pretending to speak fluent Italian to impress an artisanal pasta chef",
      "Trying to hide a smoke machine malfunction during a high-stakes job interview",
      "You accidentally challenged a local mob boss to a competitive limbo contest",
      "Faking amnesia to avoid admitting you forgot a 10th wedding anniversary",
      "You swapped identical suitcases and now possess 40 pounds of raw bratwurst",
      "A rogue roomba has dragged an open bottle of red wine across white carpet",
      "Attempting to parallel park a 40-foot RV while your in-laws shout directions",
      "You must convince a bank loan officer that your ghost-hunting business is profitable",
      "Accidentally getting your head stuck in historical wrought-iron railings",
      "Competing against your middle school bully in a county fair chili cook-off",
      "Hiding a live ferret inside a movie theater under a winter coat",
      "Your fake credentials just landed you the job of chief neurotoxin inspector",
      "A stray cat refuses to leave your lap while the building fire alarm rings",
      "You promised two different people they could be your sole heir to the same swamp",
      "Trying to assemble an IKEA bunk bed with only a butter knife before the guests arrive",
      "You must return a borrowed tuxedo that is currently covered in fondue cheese",
      "Mistakenly accepting delivery of 500 live crickets meant for a pet store",
      "Your pants split completely open right as you step up to deliver a eulogy",
      "You must convince an angry tow truck driver your vehicle is a historical monument",
      "Accidentally supergluing your hand to the steering wheel in a drive-thru",
      "Your ventriloquist dummy was entered into evidence in a grand jury trial",
      "Trying to stealthily retrieve a dropped toupee from inside an open punch bowl",
      "You accepted a duel at dawn, but your weapon of choice is a leaf blower",
      "Hiding an escaped zoo penguin in a hotel bathtub full of complimentary ice",
      "You promised to cook a five-course French dinner, but only know how to microwave hot dogs",
      "A hyper-aggressive swan is guarding your car keys on a boat ramp",
      "You accidentally signed up for a full marathon thinking it was a pub crawl",
      "Trying to explain why your carry-on luggage contains twelve jars of expired mayonnaise",
      "Your counterfeit Rolex started smoking during a handshake with your prospective boss",
      "You are stuck on a stalled ski lift next to the person who rear-ended you yesterday",
      "Faking expertise as an antique appraiser while holding a garden gnome",
      "You must smuggle a 6-foot cardboard cutout through TSA security",
      "Both of you were hired to play Santa Claus at the exact same department store shift",
      "Your smart home AI locked all doors and started playing smooth jazz at maximum volume",
      "You must win an underground arm-wrestling match to get your impounded moped back",
      "Accidentally setting off a museum alarm with an oversized foam finger",
      "Trying to discreetly dispose of a cursed porcelain doll that keeps returning to your porch",
      "You challenged a professional chess grandmaster while bluffing your way through rules",
      "A rogue Roomba trapped everyone inside an automatic sliding door vestibule",
      "You must keep an illegal backyard petting zoo hidden from the local zoning board",
      "Trying to explain why you are covered in blue dye at an airport customs checkpoint",
      "You accidentally challenged the entire bar to pay their tabs if you miss a dart throw",
      "Faking your own death to get out of a 24-month gym contract",
      "The hero is dying with regrets",
      "Researcher teaches monster the ritual mating dance, but monster thought the researcher was serious",
      "Hold up, we're being farmed for _____",
      "Two law enforcement organizations lay claim on a particular criminal case",
      "The perversity of the universe always tends toward a maximum",
      "Visions of a bad future",
      "The hero is dying without regrets",
      "We can rebuild him. We have the technology",
      "Engineered super-soldiers escape lab",
      "Safety in Muggles",
      "Killed to Uphold the Masquerade",
      "The Masquerade Will Kill Your Dating Life",
      "I have a life expectancy of a few hours",
      "The Mind Is a Plaything of the Body",
      "Why aren't the zombies here?",
      "Honor's dead, but I'll see what I can do",
      "Saving the life of someone who oppressed you",
      "Clothing stolen while we were swimming!",
      "It's Not You, It's My Enemies",
      "Impending non-consensual wedding",
      "Dungeon to crawl",
      "Who's running this simulation??!",
      "Mayfly–December Romance",
      "I hate you, Vampire dad",
      "Can't handle the stress of being magical",
      "Blessed with Suck",
      "Attempt to stop the delivery person from delivering on time to receive free pizza",
      "I want to be evil, but can't just get that pesky 'no moral compass' part down",
      "Base betrayal, even though I suggested the transformation in the first place",
      "Mate or Die",
      "Sex Signals Death",
      "Cuck actually needs to get laid",
      "Sacred Hospitality",
      "The Thing That Would Not Leave",
      "Man vs. Society",
      "Man vs. an indifferent God",
      "Man vs. a God focused on killing someone else",
      "Mistaken Identity",
      "The Corrupting Artifact",
      "The Doomsday Clock",
      "The Unavoidable Choice",
      "Enemy at the Gates",
      "A Debt Must Be Paid",
      "Trying to get debt free",
      "The False Accusation",
      "Civil War in the Ranks",
      "The Forbidden Love",
      "The Looming Plague",
      "The Incurable Curse",
      "The Blood Feud",
      "The Broken Oath",
      "The Stolen Legacy",
      "The Encroaching Darkness",
      "The Artificial Intelligence uprising... but is that ok?",
      "Keeping the evil magic alive... but why?",
      "The Prophesied Cataclysm",
      "The Dying Magic",
      "The Class Rebellion",
      "The Betrayal from Within",
      "The Forced Alliance",
      "The Invasion of the Body Snatchers",
      "The Resource Shortage",
      "The Memory Loss Paradox",
      "The Hunted Hero",
      "The Corruption of the Realm",
      "The Unchecked Ambition",
      "The Moral Dilemma",
      "The Power Struggle for the Throne",
      "The Unwanted Legacy",
      "The Time Crunch",
      "The Secret Society Threat",
      "The Monster Within",
      "The Broken Truce",
      "The Price of Salvation",
      "The Looming Famine",
      "The Clash of Faiths",
      "The Broken Vow",
      "The Sins of the Father",
      "The Unnatural Eclipse",
      "The Collapsing Dimension",
      "The False Messiah's Rise",
      "The Cursed Bloodline",
      "The Phantom Threat",
      "The Loss of Humanity",
      "The Divided Kingdom",
      "The Encroaching Ice",
      "The Unintended Consequences",
      "The Rise of the Dictator",
      "The Broken Mind",
      "The Cosmic Horror Awakening",
      "The Forbidden Knowledge",
      "The Sinking Ship",
      "The Endless Winter",
      "The Rogue Faction",
      "The Stolen Soul",
      "The Unholy Alliance",
      "The Tyrant's Ultimatum",
      "The Mutiny",
      "The Loss of Powers",
      "The Demonic Incursion",
      "The Crumbling Society",
      "The Unseen Enemy",
      "The Price of Power",
      "The Broken Family",
      "The Looming Execution",
      "The Unforgivable Crime",
      "The Eternal Rivalry",
      "The Falling Sky",
      "The Traitor in the Midst",
      "The Unholy Ritual",
      "The Loss of Memory",
      "The Corrupt System",
      "The Phantom Curse",
      "The Rising Tide",
      "The Shattered Alliance",
      "The Unstoppable Force",
      "The Forbidden Ritual",
      "The Tyrant's Decree",
      "The Dying World",
      "The Poisoned Well",
      "The Lost Key",
      "Enemies to lovers",
      "Fake relationship",
      "Love triangle",
      "Forbidden love",
      "Friends to lovers",
      "Rivals to lovers",
      "Second chance romance",
      "Marriage of convenience",
      "Mistaken identity in love",
      "Secret identity romance",
      "Class divide / star-crossed lovers",
      "Unrequited love",
      "Love at first sight vs. reality",
      "Will they or won't they?",
      "Sexual tension overload",
      "The ex-factor",
      "Office romance dilemma",
      "Bound by duty, driven by desire",
      "Bed-sharing out of necessity",
      "Love epiphany too late",
      "Dating the boss",
      "Dating the enemy's sibling",
      "Age gap relationship pressure",
      "The misunderstanding / poor communication",
      "Love triangle -> polyamory solution",
      "Seducing the target for the mission",
      "Jealousy monster strikes",
      "The contractual lovers",
      "Love across welling factions",
      "One-night stand turns into more",
      "Arranged marriage resistance",
      "The betrayal of trust",
      "Love vs. career",
      "The secret affair",
      "Chastity vow tested",
      "The best friend's ex",
      "Soulmates fated to fight",
      "Friends with benefits rules broken",
      "The guard falling for the ward",
      "The amnesiac lover",
      "Rebound relationship drama",
      "The overprotective family opposition",
      "Love spell gone wrong",
      "The matchmaker's mistake",
      "The pretend date for a wedding",
      "Lust vs. love internal struggle",
      "The love curse",
      "The forced proximity dilemma",
      "Seducing the reluctant partner",
      "The long-distance strain",
      "You must pretend to be happily married to avoid being eaten by a localized dragon",
      "Accidentally swapping bodies right before a high-stakes, multi-million dollar _____",
      "Your souls are physically tethered together by a rubber band that shrinks when you argue",
      "One partner's touch temporarily turns the other into an inanimate, highly breakable antique vase",
      "You are faking a romantic relationship to win a free lifetime supply of _____",
      "A magical curse forces you to ______ whenever you get turned on",
      "Your partner's secret identity is the literal mascot of your favorite arch-nemesis brand",
      "You accidentally signed a contract making your love life a live-streamed reality show for aliens",
      "Every time you kiss, a localized minor natural disaster occurs nearby",
      "Your rival in a high-stakes competitive knitting circuit is also your mysterious blind date",
      "You have to hide a living, screaming mandrake root",
      "Your partner turns into a werewolf, but only on full moons, and only if they eat carbs after 8 PM",
      "You are faking a romance to convince a strict HOA board to let you keep your ______",
      "A time-traveler keeps appearing to interrupt your romantic moments because your child destroys the future",
      "Your partner accidentally summoned an erotic demon who acts as an unwanted, hyper-enthusiastic third wheel",
      "A viral TikTok attracts the wrong crowd",
      "You must seduce a target, but your only dating advice comes from a 12th-century monk's diary",
      "You are cursed to speak your inner sexual thoughts out loud",
      "Your partner's ex is a ghost who aggressively haunts you to offer unsolicited critique",
      "You are trying to assassinate each other, but you both fell in love first",
      "You accidentally used a love potion on your partner's identical twin",
      "Your love language is aggressive insult-banter, but your partner takes everything literally",
      "You have to keep your relationship secret from a sentient, highly judgmental entity",
      "A rogue curse makes your clothes randomly vanish whenever you tell a minor lie",
      "You are competing against your lover for the last remaining spot in an underground bunker",
      "Your partner is convinced you are an alien imposter, but you're actually just terrible at flirting",
      "An ancient prophecy demands you two break up, but you both agree the prophecy is stupid",
      "You are pretending to be vampires to fit in at an ultra-exclusive dating club",
      "Every time you confess your feelings, the universe literally rewinds time by five minutes",
      "Your lover's family is a cult dedicated to worshipping a giant, prehistoric entity",
      "You are bound by a magical oath to never touch each other until you defeat a localized warlord",
      "Your partner turns out to be a magical entity in a trench coat trying to understand human affection",
      "You accidentally cursed your partner to experience an intense orgasm every time you _____",
      "You have to stage a fake breakup to trick a mafia boss who happens to be a huge shipper of your relationship",
      "Your partner's love language is physical touch, but you are physically made of pure electricity",
      "You are both trying to lose a bet by being the most repulsive partner possible",
      "A localized gravity anomaly keeps pulling you two toward each other at extremely inconvenient times",
      "Your partner is a shape-shifter who keeps accidentally turning into your childhood bully",
      "You accidentally consumed a potion that makes you intensely attracted to your best friend's worst habit",
      "Your romantic rival is actually yourself from an alternate dimension where you made cooler life choices",
      "You are trapped in a room that shrinks by 10% every time one of you denies their feelings",
      "Your partner's strict parents are literal, fire-breathing mythical creatures who demand a sacrifice",
      "You can only communicate your feelings through dance",
      "A curse forces you to swap kinks with a stranger",
      "You are trying to hide a massive, illegal horde of stolen art under the bed during a hookup",
      "Your lover accidentally sold your couple's origin story as a romance novel, and it's a bestseller",
      "You are forced into a fake marriage with your nemesis to secure a shared inheritance",
      "Your partner's emotional state directly controls the local weather forecast",
      "You accidentally summoned a demon lord using a cheap romantic candle during a candlelit dinner",
      "You are both trying to steal the exact same priceless diamond from each other's apartments",
      "Vines are taking over everything",
      "Something slow is stalking us",
      "Neverending snow",
      "Colonialism (we did it)",
      "Colonialism (we are the victims)",
      "Lord of the Flies",
      "I am running out of supplies on my spaceship",
      "Realizing that prizewinning hogs still go to slaughter",
      "Inventing the nuclear bomb",
      "Stranger -> brief lovers -> enemies",
      "I will NOT get back together with my ex",
      "Is it incest?",
      "Which one of us is ______?",
      "WWII",
      "Which one(s) of us will hook up",
      "God's Wrath is after your ass",
      "The War",
      "No one can know the protagonist's secret",
      "Why is the protagonist keeping the antagonist's secret?",
      "The Vietnam War",
      "The creation of an extinction-level weapon",
      "9/11",
      "Academic rivals using magic to trip each other up",
      "Divorce of convenience",
      "Marriage of convenience",
      "Dating your enemy's family",
      "Lovers to enemies",
      "The days right before a world war breaks out",
      "A predicted natural catastrophe",
      "You lose health insurance",
      "Your pen pal suddenly stops writing",
      "I have to solve _____ before the bad guy does",
      "No one believes in ______, but I know the truth",
      "We've lost contact with ______",
      "Mail keeps getting lost",
      "We keep getting instructions to a weird, unknown ritual",
      "How do I get off this fucking planet!?",
      "Am I a good farmer?",
      "Hookup culture",
      "Forbidden science gone awry",
      "Regular, mundane science gone awry",
      "Diva down!",
      "There are too many fucking dragons!",
      "Where have all the dragons gone?",
      "Peace treaty",
      "Trade agreement",
      "Which one of us can operate this fuckin' space ship?",
      "How does a dog operate a space ship designed for octopus-kind?",
      "Tax evasion gone wrong",
      "We have to breed to save the world",
      "I hate you, but we have to get married",
      "Zeus just fucked me and turned me into some sort of animal",
      "I am pregnant with a God's baby",
      "We have to find the magical object before the world ends",
      "Keep this magical baby safe",
      "Steal fire from the Gods",
      "Kill dad, marry mom",
      "God (air quotes) is just some guy (air quotes)",
      "The Gods are assholes",
      "There is no God",
      "A demon summoning gone right",
      "A demon summoning gone wrong",
      "Mold is taking over everything",
      "Oh no! We were turned into mermaids",
      "Chuck Cunningham Syndrome",
      "Villain's crime is approved by God",
      "Choose between saving one person or many",
      "Their greatest strength has become a liability",
      "They're being hunted by someone who was once family",
      "A promise they made is now impossible to keep",
      "Discover the villain was right all along",
      "Time is running out before an irreversible event",
      "Trust the one person who betrayed them",
      "Their identity is not what they always believed",
      "Two loyalties are pulling them in opposite directions",
      "The only way forward requires giving up their power",
      "They caused the disaster they're now trying to stop",
      "Someone they love is the source of the threat",
      "The truth would destroy everything they've built",
      "They must undo their life's greatest achievement",
      "A rival needs their help to survive",
      "The rules of their world have suddenly changed",
      "They're trapped reliving the same mistake",
      "Victory requires becoming what they hate most",
      "The map/plan/guide they trusted was wrong",
      "They must convince others of a truth no one wants to hear"
    ]
  },
  twist: {
    label: "Twist",
    items: [
      "The narrator has been lying the whole time",
      "The mentor was the real threat",
      "All of these catastrophes have been tests designed by a bigger villain",
      "Sword breaks... but the power was inside of you this entire time",
      "Verbal deflection right before the reveal",
      "The villain is missing",
      "The protagonist doesn't drive this story",
      "We have to sacrifice the sentient being for a burst of power",
      "Character sacrifices themselves without telling anyone",
      "You won, but you lost an arm",
      "You won, but at what cost?",
      "... but don't expect it to last",
      "Main plot and B-plot share the villain",
      "Minor Crime Reveals Major Plot",
      "Scene has little importance to the main story — until a major revelation later!!",
      "If you're gonna do something wrong, do it right!",
      "Master on the side of the slaves",
      "Undercover cops infiltrates a mobster group of undercover cops",
      "White guy passing as minority",
      "Actually, no one is coming to save you",
      "My best friend didn't come help me",
      "Your boyfriend stays at the party, even when you're in trouble",
      "All your resources (money, weapons, space ships, gasoline) are missing",
      "People with separate agendas interfering with each other's plans",
      "Birth-Death Juxtaposition",
      "Truth dismissed as the attention-seeking lie",
      "Going to the enemy for help",
      "It was my first time",
      "It was my first kill",
      "I've killed before",
      "Red Wedding",
      "(Looks around) Why are all the doors locked?",
      "Switch sides last minute, because the villain is right",
      "Villain's trauma is healed",
      "It was a mind parasite",
      "You were groomed as a child",
      "She was cheating with the milkman!",
      "Oops! We mugged the monster!",
      "Bruce Wayne Held Hostage",
      "The villain is the child of a much MUCH worse villain",
      "You didn't see the body",
      "The villain was trying to prevent something worse",
      "Decisions being made counteract each other, net zero",
      "The hero's greatest strength (weapon, ability, crew) is taken away",
      "We didn't get to the bomb fast enough",
      "Two characters are actually the same person",
      "The quest was designed to fail from the start",
      "The protagonist is already dead",
      "Time has been looping without anyone noticing",
      "The map led exactly where it was supposed to",
      "The chosen one prophecy was fabricated",
      "Everyone else can see something the protagonist can't",
      "The sidekick has been the one in control all along",
      "The world isn't as isolated as everyone believed",
      "The cure is worse than the disease",
      "Their memories were altered to hide the truth",
      "The enemy and the ally switch roles",
      "What seemed like magic is actually technology (or vice versa)",
      "The ending was the beginning all along",
      "There are too many beds in this Inn",
      "Accidentally kidnapped someone important",
      "I have no interest in getting to know my brother!",
      "The antagonist is just an abandoned automaton",
      "The cursed object wasn't causing death, it was the only thing keeping everyone alive",
      "The ally was working alongside villain to fake evidence",
      "Secret clone",
      "The haunted setting isn't full of spirits, but rather designed chaos",
      "The protagonist's imaginary friend is a real person",
      "Evidence was created in advance to frame an innocent rival",
      "You slowly realize that maybe... you're the villain in someone else's story",
      "The utopia is actually a prison",
      "Time travel fuck ups",
      "The corrupt politician was secretly funding the rebellion to keep the military budget inflated",
      "The establishment is an elaborate front to exploit participants",
      "The ancient unknowable entity who sent you on the quest actually started this whole thing",
      "Your successes borrow luck from the future",
      "The cost of magic - you further hurt the group you're trying to liberate",
      "The superpower is actually killing you",
      "The psychic future-seeing unintentionally created more baddies",
      "You're not hearing voices, it's just the ______",
      "You're not magical at all",
      "The boys in your love triangle wanted each other the entire time",
      "He's not your brother!",
      "You thought this was a simulation... but it's real!",
      "You fucked up the time travel loop",
      "He's your brother!",
      "Tomato in the mirror (You are the monster)",
      "The Mentor is the villain",
      "I Am Your Father",
      "The Unreliable Narrator",
      "The reward was a lie",
      "The reward came with stipulations",
      "Oh no, you're dead",
      "The Chosen One was a distraction",
      "You created an evil twin",
      "The trap was built for you",
      "The Cure Is Worse Than the Disease",
      "The Enemy Is Future You",
      "The Prophecy Was Fake",
      "The Utopia Is a Prison",
      "The Hero Caused the Disaster",
      "The Quest Was a Test",
      "The Monster Was Protecting Them",
      "The Ally Was a Spy",
      "The Magic Was Technology",
      "The World Is Round (Flat World Twist)",
      "The Villain Is the Hero's Child",
      "The Memory Was Fabricated",
      "The Curse Was a Blessing",
      "The Artifact Is Sentient",
      "The Timeline Has Already Loop",
      "The War Was Over Years Ago",
      "The Kingdom Never Existed",
      "The AI Was the Creator",
      "The Sidekick Is the Mastermind",
      "The Power Was Inside You All Along (Sarcastic/Literal)",
      "The Relic Is a Weapon",
      "The God Is Dead",
      "The Main Character Is the Antagonist's Vessel",
      "The Inversion of Roles",
      "The Protagonist Is the Villain's Clone",
      "The Whole World Is an Illusion",
      "The Monster Is the Last of Its Kind",
      "The Threat Was Imaginary",
      "The Prophecy Was Misinterpreted",
      "The Time Traveler Caused the Event",
      "The Hero Was the Bad Guy All Along",
      "The Sacrifice Was Pointless",
      "The Villain Controlled Both Sides",
      "The Treasure Was Trash",
      "The Haven Is Infected",
      "The Rescue Team Is the Execution Squad",
      "The Seal Was Holding Back Goodness",
      "The Ghost Is the Reader/Viewer",
      "The World Is Inside a Jar",
      "The Hero's Mentor Planned Their Death",
      "The Weapon Kills the User",
      "The Enemy Was Trying to Save Them",
      "The God Is a Child",
      "The Monster Is Human",
      "The Antagonist Is a Glitch",
      "The Legend Was Slander",
      "The Empire Has Already Fallen",
      "The Prophecy Was Self-Fulfilling",
      "The Magic System Is Powered by Souls",
      "The Chosen One Is Incompetent",
      "The Hero Failed Centuries Ago",
      "The Villain Is an Alternate Version of the Hero",
      "The Cure Kills the Host",
      "The AI Became Merciful",
      "The Realm Is Dying Because of the Hero",
      "The Monster Is a Former Hero",
      "The Memory Was Swapped",
      "The Final Boss Is a Friend",
      "The World Is an Alien Zoo",
      "The Artifact Is a Countdown",
      "The Hero Is a Hologram",
      "The Secret Society Doesn't Exist",
      "The War Was Started by the Hero's Faction",
      "The Villain Was Sacrificing Themselves",
      "The Kingdom Is Built on a Corpse",
      "The Goddess Is Evil",
      "The Portal Leads to the Past",
      "The Apocalypse Already Happened",
      "The Hero Is the Last Survivor",
      "The Antagonist Created the Hero",
      "The Magic Is Leaking",
      "The Prophecy Speaks of the Villain",
      "The fake relationship was real all along",
      "They were childhood sweethearts (forgotten memory)",
      "The matchmaker was the one in love",
      "The rival was trying to protect you, not steal your lover",
      "The one night stand is the new boss",
      "The love letter was sent to the wrong person on purpose",
      "They weren't dating, they were siblings/cousins",
      "The secret admirer is the worst enemy",
      "The arranged fiance is actually the crush",
      "The sex was a bet, but love became real",
      "The rebound was the mastermind all along",
      "The love triangle was actually a mutual attraction between all three",
      "The seduction was a trap designed by the target",
      "The ex never left—they were kidnapped, not an abandoner",
      "The chaste friend is secretly a master seducer",
      "The cold partner was overcome with hidden passion",
      "The marriage of convenience was planned years ago by one partner",
      "The love spell never worked—they just liked you",
      "The seducer fell for their own victim",
      "The affair was staged to cover up a coup",
      "The blind date is your sworn nemesis",
      "The unrequited crush was actively liked back in secret",
      "The forbidden rule didn't actually exist",
      "The escort is actually royalty in disguise",
      "The flirtatious tease is actually completely inexperienced",
      "The love letter was written by someone else entirely",
      "The contract stated they belonged together permanently",
      "The mistake night was complete design",
      "The jealous ex was secretly setting them up together",
      "The romantic rival is actually trying to date the protagonist",
      "The ultimate seduction weapon was just genuine kindness",
      "The amnesia was faked to start over in love",
      "The passionate affair was orchestrated by a matchmaking deity",
      "The enemy staged the conflict just to get close",
      "The strict boss was the anonymous romance author",
      "The best friend orchestrated every 'coincidence'",
      "The rivalry was just foreplay",
      "The sex club owner is a pure romantic at heart",
      "The starcrossed curse was a hoax",
      "The heartbreaker has never loved anyone else",
      "The proposal was rejected to test their resolve",
      "The 'other woman/man' was an hired actor",
      "The love epiphany happens right before standing at the altar",
      "The dynamic flips: the dominant becomes the submissive",
      "The seductive siren only wanted true affection",
      "The romantic paradise was created specifically for two",
      "The pretend engagement becomes legally binding",
      "The 'single' status was a secret marriage",
      "The passionate encounter awoke sleeping magic",
      "The soulmate mark belongs to the worst nemesis",
      "The romantic rival was hired by your grandma",
      "The love potion you used was actually just tap water and food coloring; the attraction was real",
      "Your mysterious lover isn't a vampire, just an extremely pale guy",
      "The soulmate mark on your arm was actually a permanent marker prank from high school",
      "The evil overlord holding you captive was actually trying to throw you a surprise blind date",
      "Your partner's ex who kept sabotaging your dates was actually their overprotective mother",
      "The secret affair you were having was actually orchestrated by your spouse to spark excitement",
      "The ghost haunting your shared house was just a very sneaky guy",
      "Your lover's secret identity isn't a superhero, but the creator of an extremely popular furry webcomic",
      "The love spell didn't work on your crush, it worked on _____",
      "The demon you summoned to be your lover is actually just an underpaid corporate temp",
      "Your partner isn't a billionaire, they just accidentally inherited 10 million shares of an obscure meme stock",
      "The whole 'enemies to lovers' rivalry was started because of a mundane mistake",
      "The spell you found was actually a highly descriptive shopping list written in Latin",
      "Your partner's tragic backstory was completely made up",
      "The mind control curse keeping you together was actually just severe mutual codependency",
      "Your lover isn't an immortal time-traveler, they just look identical to a Victorian portrait",
      "The forbidden relationship rule was made up by your friends so you two would finally get together out of spite",
      "The mysterious 'other woman' was actually your partner's identical twin",
      "The cursed artifact was a defective invention",
      "Your partner didn't forget your anniversary; they orchestrated a fake catastrophe",
      "The rival trying to break you up was actually trying to steal *you*, not your partner",
      "Your partner isn't a undercover spy",
      "The 'love curse' actually expires after three days, meaning you've just been genuinely happy",
      "The solution that saved the world is a violation of the employee handbook",
      "The secret society keeping you apart is just a local club that hates drama",
      "Your partner's tragic curse is an allergic reaction",
      "It isn't a treaty, it's an HOA handbook",
      "Your lover's mysterious disappearance was a transportation malfunction",
      "The ancient prophecy was translated incorrectly; it was actually a recipe",
      "Your partner isn't a cold, unfeeling robot; they're just extremely socially awkward",
      "The steamy romance novel was authored by your partner's dad",
      "The dark secret your partner was hiding was mundane",
      "Your lover's mob boss father is actually a nice guy",
      "The enchanted mirror didn't show your true love",
      "Your partner wasn't keeping you at arm's length because of trauma; they were just waiting for their breath mint to kick in",
      "The secret lab beneath the house was just a really elaborate home-brewing setup",
      "Your rival surrendered the fight because they realized your partner's emotional baggage was too high-maintenance",
      "The dangerous cult trying to kidnap you was actually a surprise party planning committee",
      "Your partner's magic powers were just high-level sleight-of-hand tricks they used to impress you on date one",
      "The exotic island paradise you were stranded on was actually just a private beach 50 feet from a resort",
      "Your lover's dark alter ego is just them when they get hangry before dinner",
      "The fatal flaw that was supposed to destroy your relationship is mundane",
      "The poison your lover gave you is actually psychiatric medication",
      "Your partner's immortality is just a really good skincare routine and SPF 100",
      "The alien artifact you found together was actually modern art",
      "The war between your families was started over a petty dispute during a board game",
      "Your lover's mysterious benefactor was actually their own future self sending back money",
      "The phantom haunting your bed was just your partner violently tossing and turning in their sleep",
      "The final boss you had to defeat to be together was just a very stubborn bureaucrat at the marriage license office"
    ]
  },
  tone: {
    label: "Tone",
    items: [
      "Whimsical and lighthearted",
      "Bleak and unforgiving",
      "Tense, thriller-paced",
      "A happy, joke-based plot goes into a much more serious and darker direction",
      "A once dark and deadly serious plot turns into a comedy",
      "Melancholic and reflective",
      "Absurdist and comedic",
      "Cozy and slow-burning",
      "Eerie and unsettling",
      "Epic and larger-than-life",
      "Quiet and intimate",
      "Satirical and biting",
      "Hopeful despite the odds",
      "Noir and cynical",
      "Dreamlike and surreal"
    ]
  },
  genre: {
    label: "Genre",
    items: [
      "Utopia science fiction... past humanity made all the right choices",
      "Sanderson fantasy",
      "LOTR fantasy",
      "Urban fantasy",
      "Future fantasy",
      "Mystery (murder)",
      "Age gap romance",
      "Mystery (theft)",
      "Mystery (politics)",
      "Horror (spooky)",
      "Horror (gorey)",
      "Gothic Romance",
      "Dark academia",
      "Gothic Mystery",
      "I tHinK i'M gOnnA dEe IN ThiS hoOooOOOussseEEE",
      "Reverse Harem",
      "Gay awakening",
      "Grumpy + Sunshine",
      "Cinnamon Roll Boyfriend",
      "Lesbians",
      "Enemies to Lovers",
      "Friends to Lovers",
      "Love Triangle -> Polyamory",
      "Historical fiction (you're poor)",
      "Historical fiction (you're rich)",
      "Rich girl problems",
      "University",
      "Cyberpunk",
      "Fairytale retelling",
      "Perverted fairytale",
      "The apocalypse... now what?",
      "Space opera",
      "Reality... but there's a WHIFF of magic",
      "Steampunk",
      "Superhero",
      "Slice of life"
    ]
  },
  keyObject: {
    label: "Key Object",
    items: [
      "A map that only shows where you've already been",
      "A mystical book that won't allow itself to be read",
      "A magical sex wand",
      "An ugly coat from your dad you just can't seem to donate",
      "Poisonous protein powder",
      "Medieval relic",
      "Magical apple tree",
      "An alter that calls to you",
      "You cry rose petals",
      "Something from the past that is referred to but never explained",
      "A deeply cursed Furby",
      "A single half-eaten hot dog",
      "An industrial-sized tub of Vaseline",
      "A fully functional Shake Weight",
      "A suspicious, unlabelled mason jar",
      "An oversized novelty foam finger",
      "A bedazzled catheter",
      "A pair of dirty Crocs worn in sport mode",
      "A taxidermied squirrel holding a tiny banjo",
      "An expired coupon for a free side of queso",
      "A screaming goat toy",
      "A George Foreman grill coated in grease",
      "A slightly damp cardboard box",
      "A plastic bag full of other plastic bags",
      "An aggressively vibrating massage gun",
      "A jar of pickled pigs' feet",
      "A half-melted scented candle shaped like a skull",
      "A Roomba that has gained a bad attitude",
      "A cassette tape of 90s infomercial jingles",
      "A pair of neon pink Trucker mudflap mudflaps",
      "A single, unattached prosthetic toe",
      "A rusty can of Spam from 1984",
      "A cheap, plastic luchador mask",
      "A set of chattering wind-up fake teeth",
      "A heavily stained velvet tracksuit",
      "A slightly leaking bottle of poppers",
      "An antique chamber pot filled with loose change",
      "A bag of lukewarm gas station sushi",
      "A broken lava lamp that smells like ozone",
      "A framed photo of a stranger's dog",
      "An inflatable arm-flailing tube man",
      "A half-used roll of duct tape stuck to carpet",
      "A glitter-covered dildo",
      "A deeply offensive bumper sticker",
      "A tub of lukewarm cottage cheese",
      "A worn-out pair of Trucker nuts",
      "A novelty singing bass fish mounted on the wall",
      "A container of expired Miracle Whip",
      "An empty bottle of cheap tequila",
      "A pair of light-up sketchers in adult size",
      "A pocket-sized breathalyzer that reads 'ERROR'",
      "A single leather glove covered in sequins",
      "A slightly crushed box of Lucky Charms",
      "A collection of used hotel keycards",
      "A heavily worn, oversized Snuggie",
      "A pair of fake vampire fangs from a gumball machine",
      "An empty bucket from Kentucky Fried Chicken",
      "A half-burnt stick of sage",
      "A glowing green glowstick from 2003",
      "A rusted cast-iron skillet",
      "A vibrating novelty pager from 1998",
      "An autographed 8x10 glossy headshot of Nicolas Cage",
      "A half-eaten gas station corn dog",
      "A cursed velvet fedora",
      "A pocket watch permanently stopped at 3:17",
      "A titanium crowbar with custom engravings",
      "A cracked Game Boy Color containing Pokemon Red",
      "An unopened jar of pickled pig feet",
      "A taxidermied squirrel holding a tiny banjo",
      "A vintage brass telescope with a cracked lens",
      "A stained trench coat with twenty interior pockets",
      "A solid gold toilet plunger",
      "A dented thermos full of lukewarm clam chowder",
      "A rotary telephone wired to a car battery",
      "A glowing neon 'OPEN' sign with a buzzing transformer",
      "A leather-bound diary locked with a rusty padlock",
      "A deck of marked playing cards from a 1970s casino",
      "A miniature guillotine cigar cutter",
      "A pair of fuzzy pink handcuffs with a missing key",
      "An ancient clay urn filled with loose change",
      "A broken lava lamp filled with murky sludge",
      "A motorized leaf blower modified to shoot glitter",
      "A chipped porcelain teacup with dried tea leaves",
      "An oversized foam cowboy hat",
      "A silver flask engraved with someone else's initials",
      "A portable karaoke microphone with built-in echo",
      "A rusty meat cleaver wrapped in duct tape",
      "A monocle on a frayed silk cord",
      "A disco ball covered in dried egg yolk",
      "A bowling ball with four finger holes",
      "A heavy cast-iron waffle maker",
      "A Polaroid camera with three exposures left",
      "A beaded curtain that constantly gets tangled",
      "A counterfeit luxury handbag stuffed with receipts",
      "A medieval flail made from a bike chain and a padlock",
      "A cassette tape labeled 'EVIDENCE DO NOT PLAY'",
      "A brass knuckles paperweight",
      "An antique brass spittoon",
      "A squeaky clown horn that smells like engine oil",
      "A pair of night-vision goggles held together by rubber bands",
      "A half-melted candle shaped like a skull",
      "An accordion missing two key buttons",
      "A Swiss Army knife with every tool deployed",
      "A leather bullwhip with mold on the handle",
      "A stained trucker hat with a dubious slogan",
      "A handheld CB radio picking up phantom chatter",
      "A bowling trophy with the figurine's head snapped off",
      "A heavy wool blanket with cigarette burn holes",
      "A wooden peg leg fitted with a hidden flask",
      "A homecooked meal that fixes everything",
      "A can of root beer you were saving for later",
      "An empty pantry",
      "A diary you never got around to writing in",
      "Collection of random items, used as weapon",
      "Items with Edutainment quality",
      "Dog guarding something mysterious",
      "Prop that adds atmosphere to a setting. Fans speculate wildly",
      "Improvised clothing",
      "Chekhov's Gun",
      "A running gag",
      "A mysterious, blank invitation",
      "An obvious, plausible workaround the character's can't think of",
      "Chaste Separating Sword",
      "Pizza in 30 Minutes, or It's Free!",
      "The DO-NO-REMOVE tag on your mattress",
      "How DID that guy get his nickname?",
      "A perpetual stew",
      "A perpetual flame",
      "A mysterious flask that probably has a powerful demon in it",
      "Knife of a king found at a flea market",
      "Armor you had to steal",
      "Dead mom's ring",
      "A decoy object",
      "Magical object mistaken for Mall Goth trinket",
      "A suspicious photograph of your parents and their friends",
      "A relic used to kill your God",
      "A cat",
      "A magical blade",
      "A letter that was never meant to be delivered",
      "A pocket watch that runs backward",
      "A book that writes itself",
      "A key with no matching lock (yet)",
      "A mirror that shows who you could become",
      "A seed that grows memories instead of plants",
      "An instrument that plays other people's emotions",
      "A coin that always lands on the outcome you fear",
      "A cloak that makes you forgettable, not invisible",
      "A recipe passed down with a hidden meaning",
      "A photograph of a place that no longer exists"
    ]
  },
  timePeriod: {
    label: "Time Period",
    items: [
      "Dinosaurs",
      "Stone tools, fur loincloths",
      "We just got metal, let's build a sword",
      "Pagan, pre-Christ",
      "Pagan, post-Christ",
      "Birth of Christ",
      "Aftermath of Christianity",
      "Christianity Gone Wild! Medieval",
      "Medieval",
      "English Colonialism",
      "Elizabethan Court",
      "Victorians Doing Weird Stuff",
      "Roaring 1920s",
      "20th Century Poor",
      "20th Century Rich",
      "World-War Chic",
      "20th Century War",
      "War with Swords",
      "War with lasers",
      "War with insane technology",
      "1980s uptown funk",
      "1970s rural",
      "Y2K panic",
      "The internet is just being born",
      "Contemporary (rich)",
      "Contemporary (poor)",
      "Present day, with magic",
      "Near future (10-30 years)",
      "Farrrrrrrr future",
      "An alternate history where a key event went differently",
      "Time Loop",
      "Same event, mirrored across time",
      "Pre-Cambrian primordial soup swimming",
      "First creature crawling onto land",
      "Ice Age megafauna",
      "Pyramid building and river valley empires",
      "Bronze Age collapse and chaos",
      "Silk Road merchant caravans",
      "Classical Greece philosophy & tragedy",
      "Golden Age of Piracy",
      "Renaissance",
      "Wild West frontier expansion",
      "Industrial Revolution smog and coal",
      "1950s suburban atomic optimism",
      "1960s counterculture and moon landing",
      "1990s mall culture and VHS tapes",
      "Cyberpunk neon megacity",
      "Solarpunk eco-utopia",
      "Post-apocalyptic wasteland scavenging",
      "Intergalactic colonization era",
      "Heat death of the universe",
      "Microscopic cellular organisms eating each other",
      "Volcanic Earth cooling down",
      "Rise of the giant insects Carboniferous era",
      "First human discovery of fermented alcohol",
      "Neolithic farming revolution and first permanent villages",
      "Sumerian cuneiform tablet accounting",
      "Babylonian lawmaking and astrology",
      "Minoan palace life and bull-leaping",
      "Warring States period chariot battles",
      "Hellenistic library hoarders in Alexandria",
      "Viking longship coastal raids",
      "Islamic Golden Age mathematics and medicine",
      "Mongol steppe unification and horse archers",
      "Mesoamerican stepped pyramid ritual sacrifices",
      "Edo period feudal Japan isolationism",
      "Age of Enlightenment coffee house debates",
      "French Revolution guillotine drama",
      "Gold Rush boomtown lawlessness",
      "Scramble for Africa resource plundering",
      "Steampunk airship fleet voyages",
      "WWI biplane dogfights and mustard gas",
      "Prohibition speakeasy bootlegging",
      "Dust Bowl migrant caravans",
      "Cold War nuclear bunker paranoia",
      "Disco fever rollerskating 1970s",
      "1980s Wall Street greed and hair metal",
      "2000s garage band revival and emo phase",
      "Early 2010s hipster coffee and blog culture",
      "Generative AI singularity panic",
      "Underwater Sub-aquatic dome cities",
      "Orbital space station habitat blue-collar work",
      "Terraforming Mars dusty pioneer era",
      "Generation ship multigenerational voyage",
      "Dyson sphere construction project",
      "Matrix-style simulated reality matrix",
      "Post-scarcity digital consciousness upload",
      "Galactic empire feudal decline",
      "Dimensional invasion war",
      "Time travel tourist agency golden age"
    ]
  }
};

// Beat sheet prompts for the fine-tune workshop, based on the "Save the Cat!"
// beat sheet (https://savethecat.com/how-to-write-a-novel). Free-text only,
// no randomizer.
const OUTLINE_FIELDS = [
  {
    key: "openingImage",
    label: "Opening Image",
    act: "Act 1 — The Ordinary World",
    placeholder: "0–1%: A snapshot of the hero before transformation. Sets the tone."
  },
  {
    key: "themeStated",
    label: "Theme Stated",
    act: "Act 1 — The Ordinary World",
    placeholder: "5%: Someone poses the question or statement the story is really about."
  },
  {
    key: "setUp",
    label: "Set-Up",
    act: "Act 1 — The Ordinary World",
    placeholder: "1–10%: Establish the hero's ordinary life, flaws, and world."
  },
  {
    key: "catalyst",
    label: "Catalyst",
    act: "Act 1 — The Ordinary World",
    placeholder: "10%: The life-changing event that sets the story in motion."
  },
  {
    key: "debate",
    label: "Debate",
    act: "Act 1 — The Ordinary World",
    placeholder: "10–20%: The hero hesitates. Should they really go on this journey?"
  },
  {
    key: "breakIntoTwo",
    label: "Break into Two",
    act: "Act 2 — The Upside-Down World",
    placeholder: "20%: The no-turning-back decision into a new world or mindset."
  },
  {
    key: "bStory",
    label: "B Story",
    act: "Act 2 — The Upside-Down World",
    placeholder: "22%: A secondary story (love, friendship, mentorship) that carries the theme."
  },
  {
    key: "funAndGames",
    label: "Fun and Games",
    act: "Act 2 — The Upside-Down World",
    placeholder: "20–50%: The 'promise of the premise' — what the trailer would show."
  },
  {
    key: "midpoint",
    label: "Midpoint",
    act: "Act 2 — The Upside-Down World",
    placeholder: "50%: A false victory or false defeat that raises the stakes."
  },
  {
    key: "badGuysCloseIn",
    label: "Bad Guys Close In",
    act: "Act 2 — The Upside-Down World",
    placeholder: "50–75%: External and internal pressure mounts on the hero."
  },
  {
    key: "allIsLost",
    label: "All Is Lost",
    act: "Act 2 — The Upside-Down World",
    placeholder: "75%: The hero's worst fear comes true. Often a 'whiff of death.'"
  },
  {
    key: "darkNightOfTheSoul",
    label: "Dark Night of the Soul",
    act: "Act 2 — The Upside-Down World",
    placeholder: "75–80%: The hero hits bottom and sits with everything they've lost."
  },
  {
    key: "breakIntoThree",
    label: "Break into Three",
    act: "Act 3 — Merged World",
    placeholder: "80%: New information reveals the solution to Act Two's problems."
  },
  {
    key: "finale",
    label: "Finale",
    act: "Act 3 — Merged World",
    placeholder: "80–99%: The climax, where the hero proves their change through action."
  },
  {
    key: "finalImage",
    label: "Final Image",
    act: "Act 3 — Merged World",
    placeholder: "99–100%: A bookend to the Opening Image, showing how far things came."
  }
];
