// Story element categories. Each key is a category; edit/add items freely.
const CATEGORIES = {
  character: {
    label: "Character",
    items: [
      "A retired superhero who's lost their powers",
      "A small-town librarian with a hidden past",
      "An AI that just became self-aware",
      "A washed-up detective on their last case",
      "A teenager who can talk to ghosts",
      "A con artist trying to go straight",
      "An immortal who's forgotten why they wanted to live forever",
      "A soldier who refuses to fight anymore",
      "A chef who can taste memories in food",
      "A courier who delivers messages between worlds",
      "A scientist whose experiment became sentient",
      "A grieving parent searching for answers",
      "A thief who only steals from the wealthy",
      "A child prodigy burned out by expectations",
      "A lighthouse keeper who sees things in the fog",
      "A former villain seeking redemption",
      "A time traveler stuck in the wrong era",
      "A ship captain who's never lost a crew member",
      "A hermit dragged back into society",
      "A clone questioning their own identity",
      "Spider-Man",
      "Batman",
      "Superman",
      "Wonder Woman",
      "Iron Man",
      "Captain America",
      "The Hulk",
      "Wolverine",
      "Black Panther",
      "Harry Potter",
      "Hermione Granger",
      "Frodo Baggins",
      "Aragorn",
      "Luke Skywalker",
      "Princess Leia",
      "Han Solo",
      "Katniss Everdeen",
      "Sherlock Holmes",
      "James Bond",
      "Indiana Jones",
      "Ellen Ripley",
      "Sarah Connor",
      "Neo",
      "John Wick",
      "Jon Snow",
      "Daenerys Targaryen",
      "Rocky Balboa",
      "Elsa",
      "Moana",
      "Mulan",
      "Beetlejuice (the dog)",
      "Wicked Witch of the West",
      "Princess Bride",
      "The Witcher",
      "Neil Gaiman",
      "A fascist police dog",
      "Snape",
      "Dumbledor",
      "Ebenezer Scrooge",
      "Soulmates fated to kill each other",
      "Romeo and/or Juliet",
      "Peter Pan",
      "Murder Robot",
      "Nancy Drew",
      "Lindsey Clancy",
      "A talking dragon who guards a magical gate in the middle of the harbor",
      "A serial killer, but he's kinda right...",
      "A loyal bodyguard in love with his ward's wife",
      "An assassin of the Catholic church",
      "A sex club owner",
      "Akasha, Queen of the Damned",
      "Omniscient, unknowable horror",
      "An invisible person trying desperately to communicate",
      "Astarion",
      "A prostitute who's trying to get into law enforcement, but keeps getting rejected",
      "A self-help guru",
      "A TikTok astrologer receiving signals from street lamps",
      "Caligula",
      "An Instagram influencer",
      "A group of awful jocks bullying you",
      "A masked hero, and you just know he's hot",
      "Gordon Ramsey",
      "Villain who is selectively nice to very specific people",
      "A good kid pressured into altering records to commit a crime",
      "Someone born to provide harvested organs",
      "An organ harvester who contracts HIV from a sale",
      "Barbie",
      "A duty-bound knight who just keeps fuckin' (hates himself)",
      "A duty-bound knight who cannot stop accidentally killing his wards",
      "Nightmare neighbor with numerous weapons charges",
      "Stuart Little",
      "A plucky teenager who keeps getting thrown in prison (did they commit the crime???)",
      "A guy who SOMEHOW keeps escaping prison",
      "A stern man that just wants to be SENT HOME",
      "Someone missing their favorite show on TV",
      "Falsely accused, just released",
      "Fitness guru, but doesn't know they're a demigod",
      "Simba",
      "A bureaucrat enforcing an unjust law",
      "A former ally who now sees things differently",
      "A force of nature given a will of its own",
      "An idealist willing to do anything for their cause",
      "A version of the protagonist from another timeline",
      "A version of themself from another timeline",
      "A corporation that owns the concept of memory",
      "A god who wants to be forgotten",
      "An AI optimizing for the 'wrong' outcome",
      "A parent who won't let go",
      "A cult that believes the end is a gift",
      "A rival who is simply better, most of the time",
      "Society itself, and its quiet cruelties",
      "A monster that used to be human",
      "A judge who is never wrong, and never merciful",
      "A beautiful statue, come to life",
      "Icarus",
      "Darth Vader",
      "Emperor Palpatine",
      "Voldemort",
      "Sauron",
      "The Joker",
      "Thanos",
      "Magneto",
      "Lex Luthor",
      "A prince on the run",
      "An oppressed race with a rich culture",
      "Green Goblin",
      "Doctor Doom",
      "Loki",
      "Hannibal Lecter",
      "Dracula",
      "Freddy Krueger",
      "Michael Myers",
      "Agent Smith",
      "The Terminator",
      "HAL 9000",
      "A nymphomaniac sex slave",
      "A newly-freed slave",
      "Cruella de Vil",
      "Ursula",
      "Maleficent",
      "Scar",
      "Jafar",
      "Bane",
      "Ramsay Bolton",
      "Cersei Lannister",
      "Moriarty",
      "Gollum",
      "The Gladiator",
      "Pete Davidson",
      "Charli XCX",
      "Obama",
      "Ariana Grande",
      "Frankenstein",
      "Moby Dick (the guy)",
      "Moby Dick (the whale)",
      "Straight-passing gay person",
      "Gay-passing straight person who just wants to fit in",
      "A giant",
      "A twink that doesn't know how he got here",
      "Bella",
      "An absolute diva",
      "A gym bro",
      "Buzz Lightyear",
      "Miss Piggy",
      "Kermit",
      "Paul Atreides",
      "A cursed man who does everything to thwart fate",
      "False messiah",
      "James Bond",
      "An all-around good guy not expecting to get thrust into this nonsense",
      "A Warhammer 40k player",
      "A notorious liar",
      "He's the Chosen One... but is mad about it",
      "A poacher",
      "A MAGA convert",
      "Another character's evil counterpart",
      "A compulsive thief",
      "An apprentice and their teacher",
      "Rand al'Thor",
      "Moiraine and Lan",
      "Legolas",
      "A mystic (stinky hippie with dreads)",
      "An oracle that's too beautiful for words",
      "A mystic addicted to the drug they need to see the future",
      "A foster kid",
      "A hot CEO",
      "Sexy Demon",
      "Cannibal Demon",
      "Real estate agent",
      "Peter Lister",
      "David Hertel",
      "Circus performer",
      "A goth DJ",
      "The Hulk (reformed)",
      "The leader of a frat initiation ritual",
      "Nancy Grace",
      "Fox News anchor",
      "Soup kitchen chef with a secret",
      "Jacob",
      "Edward",
      "A magical baby",
      "A baby you REALLY don't want to be around",
      "A child who knows more than they let on",
      "An estranged sibling seeking reconciliation",
      "A rival turned reluctant ally",
      "A mentor hiding a terminal secret",
      "Really nice guy who hates only you",
      "Himbo CEO who runs business into the ground",
      "Someone faking amnesia",
      "The antagonist's sibling",
      "A classroom of college kids",
      "An after-hours adult-learning Spanish class",
      "A line cook",
      "A stranger who shows up at the worst/best moment",
      "An animal companion who understands more than expected",
      "A bureaucrat quietly helping from the shadows",
      "An old flame with unfinished business",
      "A ghost who won't move on until a debt is settled",
      "A con artist who becomes an unlikely friend",
      "Hot preacher sent to convert by all means necessary",
      "Unhot preacher sent to convert by all means necessary",
      "Hot nun who loves her God",
      "Unhot nun who loves to sin",
      "A newly-elected figurehead to a powerful religion",
      "A sentient object that wants to be destoryed",
      "Mermaid, wishing for legs",
      "A girl boosting her self esteem by sleeping with priests",
      "Vindictive clergy",
      "Bad actions, but he's a good guy",
      "A sentient bug",
      "Michael Scott",
      "Ron Swanson",
      "Leslie Knope",
      "Dwight Schrute",
      "Homer Simpson",
      "SpongeBob SquarePants",
      "Shrek",
      "Jack Sparrow",
      "Buffy Summers",
      "Walter White",
      "Tony Soprano",
      "Ross Geller",
      "Ferris Bueller",
      "Napoleon Dynamite",
      "Marty McFly",
      "The Dude",
      "Forrest Gump",
      "Tyrion Lannister",
      "Ash Ketchum",
      "Goku",
      "Naruto Uzumaki",
      "Deadpool",
      "Star-Lord",
      "Michael Jordan",
      "Oprah Winfrey",
      "Barack Obama",
      "Steve Jobs",
      "Beyoncé",
      "Taylor Swift",
      "Kanye West",
      "Britney Spears",
      "Michael Jackson",
      "Tom Brady",
      "LeBron James",
      "Dwayne \"The Rock\" Johnson",
      "Will Smith",
      "Justin Bieber",
      "Lady Gaga",
      "Serena Williams",
      "Mark Zuckerberg",
      "Elon Musk",
      "Ellen DeGeneres",
      "Eminem",
      "Rihanna"
    ]
  },
  setting: {
    label: "Setting",
    items: [
      "A city that rearranges itself every night",
      "The last library on Earth",
      "A generation ship nearing its destination",
      "A small coastal town where the tide never goes out",
      "The border between two warring kingdoms",
      "A university for retired gods",
      "An underground railway that runs through time",
      "A never-ending story that traps its readers",
      "A floating market above the clouds",
      "A post-apocalyptic greenhouse city",
      "A carnival that only appears once a decade",
      "The inside of a dying star",
      "A village where everyone shares one dream",
      "A courtroom that judges fictional characters",
      "An archive of forgotten memories",
      "A desert where sound turns solid",
      "A hotel that exists between dimensions",
      "A subway system with no exits",
      "A frozen ocean hiding a sunken civilization",
      "A theater where the plays predict the future",
      "A labyrinth (sexy)",
      "A law firm",
      "Military academy in space",
      "A magical academy tucked away from sight",
      "Little House on the Prairie",
      "Wuthering Heights",
      "Jurassic Park",
      "Waffle House",
      "Southern Gothic Waffle House",
      "Wonderland (Alice)",
      "Paradise (trying to eat you)",
      "Paradise (seems alright!)",
      "Treasure Island",
      "Mystical location of ascension",
      "BDSM society",
      "Monster fighting pits",
      "Battle planet",
      "The inside of a leviathan brain",
      "A dying planet",
      "Our dad's abandoned throne room",
      "A castle that wants to keep you hostage",
      "A castle that wants you to fuuuuuuuuuuuuck",
      "A thriving planet... but where are the living creatures?",
      "A walled city",
      "A coliseum",
      "A labyrinth (scary)",
      "Yellowstone National Park",
      "Monster's Inc.",
      "Haunted Hotel",
      "Luxury Train",
      "Surveillance State",
      "Magical world hidden in plain sight",
      "A dirt and stick house, hastily assembled",
      "Desert",
      "Pawn Shop",
      "Vaguely Scottish magic land",
      "Mr Roger's Neighborhood",
      "The Underworld",
      "A sweaty basement",
      "A post-catastrophe city with a giant hole in the middle",
      "A shitty apartment with a negligent landlord",
      "The planet from Dune",
      "Nursing home",
      "Archaeology that hint at magic"
    ]
  },
  conflict: {
    label: "Conflict",
    items: [
      "Vines are taking over everything",
      "Something slow is stalking us",
      "Neverending snow",
      "Colonialism (we did it)",
      "Colonialism (we are the victims)",
      "Lord of the Flies",
      "I am running out of supplies on my spaceship",
      "Realizing that prizewinning hogs still go to slaughter",
      "Inventing the nuclear bomb",
      "Stranger -> brief lovers -> enemies",
      "I will NOT get back together with my ex",
      "Is it incest?",
      "Which one of us is ______?",
      "WWII",
      "Which one(s) of us will hook up",
      "God's Wrath is after your ass",
      "The War",
      "No one can know the protagonist's secret",
      "Why is the protagonist keeping the antagonist's secret?",
      "The Vietnam War",
      "The creation of an extinction-level weapon",
      "9/11",
      "Academic rivals using magic to trip each other up",
      "Divorce of convenience",
      "Marriage of convenience",
      "Dating your enemy's family",
      "Lovers to enemies",
      "The days right before a world war breaks out",
      "A predicted natural catastrophe",
      "You lose health insurance",
      "Your pen pal suddenly stops writing",
      "I have to solve _____ before the bad guy does",
      "No one believes in ______, but I know the truth",
      "We've lost contact with ______",
      "Mail keeps getting lost",
      "We keep getting instructions to a weird, unknown ritual",
      "How do I get off this fucking planet!?",
      "Am I a good farmer?",
      "Hookup culture",
      "Forbidden science gone awry",
      "Regular, mundane science gone awry",
      "Diva down!",
      "There are too many fucking dragons!",
      "Where have all the dragons gone?",
      "Peace treaty",
      "Trade agreement",
      "Which one of us can operate this fuckin' space ship?",
      "How does a dog operate a space ship designed for octopus-kind?",
      "Tax evasion gone wrong",
      "We have to breed to save the world",
      "I hate you, but we have to get married",
      "Zeus just fucked me and turned me into some sort of animal",
      "I am pregnant with a God's baby",
      "We have to find the magical object before the world ends",
      "Keep this magical baby safe",
      "Steal fire from the Gods",
      "Kill dad, marry mom",
      "God (air quotes) is just some guy (air quotes)",
      "The Gods are assholes",
      "There is no God",
      "A demon summoning gone right",
      "A demon summoning gone wrong",
      "Mold is taking over everything",
      "Oh no! We were turned into mermaids",
      "Choose between saving one person or many",
      "Their greatest strength has become a liability",
      "They're being hunted by someone who was once family",
      "A promise they made is now impossible to keep",
      "Discover the villain was right all along",
      "Time is running out before an irreversible event",
      "Trust the one person who betrayed them",
      "Their identity is not what they always believed",
      "Two loyalties are pulling them in opposite directions",
      "The only way forward requires giving up their power",
      "They caused the disaster they're now trying to stop",
      "Someone they love is the source of the threat",
      "The truth would destroy everything they've built",
      "They must undo their life's greatest achievement",
      "A rival needs their help to survive",
      "The rules of their world have suddenly changed",
      "They're trapped reliving the same mistake",
      "Victory requires becoming what they hate most",
      "The map/plan/guide they trusted was wrong",
      "They must convince others of a truth no one wants to hear"
    ]
  },
  twist: {
    label: "Twist",
    items: [
      "The narrator has been lying the whole time",
      "The mentor was the real threat",
      "The 'villain' was trying to prevent something worse",
      "Two characters are actually the same person",
      "The quest was designed to fail from the start",
      "The protagonist is already dead",
      "Time has been looping without anyone noticing",
      "The map led exactly where it was supposed to",
      "The 'chosen one' prophecy was fabricated",
      "Everyone else can see something the protagonist can't",
      "The sidekick has been the one in control all along",
      "The world isn't as isolated as everyone believed",
      "The cure is worse than the disease",
      "Their memories were altered to hide the truth",
      "The enemy and the ally switch roles",
      "What seemed like magic is actually technology (or vice versa)",
      "The ending was the beginning all along",
      "There are too many beds in this Inn",
      "Accidentally kidnapped someone important",
      "I have no interest in getting to know my brother!",
      "The antagonist is just an abandoned automaton.",
      "The cursed object wasn't causing death, it was the only thing keeping everyone alive.",
      "The ally was working alongside villain to fake evidence.",
      "Secret clone.",
      "The haunted setting isn't full of spirits, but rather designed chaos.",
      "The protagonist's imaginary friend is a real person.",
      "Evidence was created in advance to frame an innocent rival.",
      "You slowly realize that maybe... you're the villain in someone else's story.",
      "The utopia is actually a prison.",
      "Time travel fuck ups.",
      "The corrupt politician was secretly funding the rebellion to keep the military budget inflated.",
      "The establishment is an elaborate front to exploit participants.",
      "The ancient unknowable entity who sent you on the quest actually started this whole thing.",
      "Your successes borrow luck from the future.",
      "The cost of magic - you further hurt the group you're trying to liberate",
      "The superpower is actually killing you",
      "The psychic future-seeing unintentionally created more baddies.",
      "You're not hearing voices, it's just the ______.",
      "You're not magical at all",
      "The boys in your love triangle wanted each other the entire time",
      "He's not your brother!",
      "You thought this was a simulation... but it's real!",
      "You fucked up the time travel loop",
      "He's your brother!"
    ]
  },
  tone: {
    label: "Tone",
    items: [
      "Whimsical and lighthearted",
      "Bleak and unforgiving",
      "Tense, thriller-paced",
      "Melancholic and reflective",
      "Absurdist and comedic",
      "Cozy and slow-burning",
      "Eerie and unsettling",
      "Epic and larger-than-life",
      "Quiet and intimate",
      "Satirical and biting",
      "Hopeful despite the odds",
      "Noir and cynical",
      "Dreamlike and surreal"
    ]
  },
  genre: {
    label: "Genre",
    items: [
      "Utopia science fiction... past humanity made all the right choices",
      "Sanderson fantasy",
      "LOTR fantasy",
      "Urban fantasy",
      "Future fantasy",
      "Mystery (murder)",
      "Age gap romance",
      "Mystery (theft)",
      "Mystery (politics)",
      "Horror (spooky)",
      "Horror (gorey)",
      "Gothic Romance",
      "Dark academia",
      "Gothic Mystery",
      "I tHinK i'M gOnnA dEe IN ThiS hoOooOOOussseEEE",
      "Reverse Harem",
      "Gay awakening",
      "Grumpy + Sunshine",
      "Cinnamon Roll Boyfriend",
      "Lesbians",
      "Enemies to Lovers",
      "Friends to Lovers",
      "Love Triangle -> Polyamory",
      "Historical fiction (you're poor)",
      "Historical fiction (you're rich)",
      "Rich girl problems",
      "University",
      "Cyberpunk",
      "Fairytale retelling",
      "Perverted fairytale",
      "The apocalypse... now what?",
      "Space opera",
      "Reality... but there's a WHIFF of magic",
      "Steampunk",
      "Superhero",
      "Slice of life"
    ]
  },
  keyObject: {
    label: "Key Object",
    items: [
      "A map that only shows where you've already been",
      "A mystical book that won't allow itself to be read",
      "A magical sex wand",
      "An ugly coat from your dad you just can't seem to donate",
      "Poisonous protein powder",
      "Medieval relic",
      "Magical apple tree",
      "An alter that calls to you",
      "You cry rose petals",
      "A suspicious photograph of your parents and their friends",
      "A relic used to kill your God",
      "A cat",
      "A magical blade",
      "A letter that was never meant to be delivered",
      "A pocket watch that runs backward",
      "A book that writes itself",
      "A key with no matching lock (yet)",
      "A mirror that shows who you could become",
      "A seed that grows memories instead of plants",
      "An instrument that plays other people's emotions",
      "A coin that always lands on the outcome you fear",
      "A cloak that makes you forgettable, not invisible",
      "A recipe passed down with a hidden meaning",
      "A photograph of a place that no longer exists"
    ]
  },
  timePeriod: {
    label: "Time Period",
    items: [
      "Dinosaurs",
      "Stone tools, fur loincloths",
      "We just got metal, let's build a sword",
      "Pagan, pre-Christ",
      "Pagan, post-Christ",
      "Birth of Christ",
      "Aftermath of Christianity",
      "Christianity Gone Wild! Medieval",
      "Medieval",
      "English Colonialism",
      "Elizabethan Court",
      "Victorians Doing Weird Stuff",
      "Roaring 1920s",
      "20th Century Poor",
      "20th Century Rich",
      "World-War Chic",
      "20th Century War",
      "War with Swords",
      "War with lasers",
      "War with insane technology",
      "1980s uptown funk",
      "1970s rural",
      "Y2K panic",
      "The internet is just being born",
      "Contemporary (rich)",
      "Contemporary (poor)",
      "Present day, with magic",
      "Near future (10-30 years)",
      "Farrrrrrrr future",
      "An alternate history where a key event went differently",
      "Time Loop",
      "Same event, mirrored across time"
    ]
  }
};

// Beat sheet prompts for the fine-tune workshop, based on the "Save the Cat!"
// beat sheet (https://savethecat.com/how-to-write-a-novel). Free-text only,
// no randomizer.
const OUTLINE_FIELDS = [
  {
    key: "openingImage",
    label: "Opening Image",
    act: "Act 1 — The Ordinary World",
    placeholder: "0–1%: A snapshot of the hero before transformation. Sets the tone."
  },
  {
    key: "themeStated",
    label: "Theme Stated",
    act: "Act 1 — The Ordinary World",
    placeholder: "5%: Someone poses the question or statement the story is really about."
  },
  {
    key: "setUp",
    label: "Set-Up",
    act: "Act 1 — The Ordinary World",
    placeholder: "1–10%: Establish the hero's ordinary life, flaws, and world."
  },
  {
    key: "catalyst",
    label: "Catalyst",
    act: "Act 1 — The Ordinary World",
    placeholder: "10%: The life-changing event that sets the story in motion."
  },
  {
    key: "debate",
    label: "Debate",
    act: "Act 1 — The Ordinary World",
    placeholder: "10–20%: The hero hesitates. Should they really go on this journey?"
  },
  {
    key: "breakIntoTwo",
    label: "Break into Two",
    act: "Act 2 — The Upside-Down World",
    placeholder: "20%: The no-turning-back decision into a new world or mindset."
  },
  {
    key: "bStory",
    label: "B Story",
    act: "Act 2 — The Upside-Down World",
    placeholder: "22%: A secondary story (love, friendship, mentorship) that carries the theme."
  },
  {
    key: "funAndGames",
    label: "Fun and Games",
    act: "Act 2 — The Upside-Down World",
    placeholder: "20–50%: The 'promise of the premise' — what the trailer would show."
  },
  {
    key: "midpoint",
    label: "Midpoint",
    act: "Act 2 — The Upside-Down World",
    placeholder: "50%: A false victory or false defeat that raises the stakes."
  },
  {
    key: "badGuysCloseIn",
    label: "Bad Guys Close In",
    act: "Act 2 — The Upside-Down World",
    placeholder: "50–75%: External and internal pressure mounts on the hero."
  },
  {
    key: "allIsLost",
    label: "All Is Lost",
    act: "Act 2 — The Upside-Down World",
    placeholder: "75%: The hero's worst fear comes true. Often a 'whiff of death.'"
  },
  {
    key: "darkNightOfTheSoul",
    label: "Dark Night of the Soul",
    act: "Act 2 — The Upside-Down World",
    placeholder: "75–80%: The hero hits bottom and sits with everything they've lost."
  },
  {
    key: "breakIntoThree",
    label: "Break into Three",
    act: "Act 3 — Merged World",
    placeholder: "80%: New information reveals the solution to Act Two's problems."
  },
  {
    key: "finale",
    label: "Finale",
    act: "Act 3 — Merged World",
    placeholder: "80–99%: The climax, where the hero proves their change through action."
  },
  {
    key: "finalImage",
    label: "Final Image",
    act: "Act 3 — Merged World",
    placeholder: "99–100%: A bookend to the Opening Image, showing how far things came."
  }
];
